
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\procedimientos\crud_transaccion.sql"


-- >> CREATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_TRANSACCION (
    P_ID_USER         IN  TRANSACCION.ID_USER%TYPE,
    P_ID_PRESUPUESTO  IN  TRANSACCION.ID_PRESUPUESTO%TYPE,
    P_ID_SUBCATEGORIA IN  TRANSACCION.ID_SUBCATEGORIA%TYPE,
    P_ANIO            IN  TRANSACCION.ANIO%TYPE,
    P_MES             IN  TRANSACCION.MES%TYPE,
    P_TIPO            IN  TRANSACCION.TIPO%TYPE,
    P_DESCRIPCION     IN  TRANSACCION.DESCRIPCION%TYPE,
    P_MONTO           IN  TRANSACCION.MONTO%TYPE,
    P_FECHA           IN  TRANSACCION.FECHA_TRANSACCION%TYPE,
    P_METODO_PAGO     IN  TRANSACCION.METODO_PAGO%TYPE,
    P_NUM_FACTURA     IN  TRANSACCION.NUM_FACTURA%TYPE,
    P_OBSERVACIONES   IN  TRANSACCION.OBSERVACIONES%TYPE,
    P_ID_GENERADO     OUT TRANSACCION.ID_TRANSACCION%TYPE
) AS
    V_TIPO_SUBCAT VARCHAR2(10);
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20150, 'El monto de la transaccion debe ser mayor a cero.');
    END IF;
    IF TRIM(P_DESCRIPCION) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20151, 'La descripcion es obligatoria.');
    END IF;
    IF P_FECHA > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20152, 'La fecha de transaccion no puede ser futura.');
    END IF;

    -- Validar que el tipo coincida con la subcategoria
    SELECT C.TIPO INTO V_TIPO_SUBCAT
    FROM   SUBCATEGORIA S
    INNER JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF V_TIPO_SUBCAT != P_TIPO THEN
        RAISE_APPLICATION_ERROR(-20153,
            'El tipo "' || P_TIPO || '" no coincide con el tipo de la subcategoria "' || V_TIPO_SUBCAT || '".');
    END IF;

    INSERT INTO TRANSACCION (
        ID_TRANSACCION, ID_USER, ID_PRESUPUESTO,
        ID_SUBCATEGORIA, ANIO, MES, TIPO,
        DESCRIPCION, MONTO, FECHA_TRANSACCION,
        METODO_PAGO, NUM_FACTURA, OBSERVACIONES,
        FECHA_HORA_REGISTRO
    ) VALUES (
        NULL, P_ID_USER, P_ID_PRESUPUESTO,
        P_ID_SUBCATEGORIA, P_ANIO, P_MES, P_TIPO,
        P_DESCRIPCION, P_MONTO, P_FECHA,
        P_METODO_PAGO, P_NUM_FACTURA, P_OBSERVACIONES,
        SYSTIMESTAMP
    ) RETURNING ID_TRANSACCION INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la subcategoria indicada.');
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_TRANSACCION;
/

-- >> READ (uno por ID)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_TRANSACCION (
    P_ID_TRANSACCION IN  TRANSACCION.ID_TRANSACCION%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  T.*,
                S.NOMBRE AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE AS NOMBRE_CATEGORIA
        FROM    TRANSACCION  T
        INNER JOIN    SUBCATEGORIA S ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        INNER JOIN    CATEGORIA    C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   T.ID_TRANSACCION = P_ID_TRANSACCION;
END SP_CONSULTAR_TRANSACCION;
/

-- >> READ (todos)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_TRANSACCIONES (
    P_ID_PRESUPUESTO IN  TRANSACCION.ID_PRESUPUESTO%TYPE,
    P_ANIO           IN  TRANSACCION.ANIO%TYPE,
    P_MES            IN  TRANSACCION.MES%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  T.ID_TRANSACCION, T.FECHA_TRANSACCION,
                T.ANIO, T.MES, T.TIPO,
                C.NOMBRE  AS NOMBRE_CATEGORIA,
                S.NOMBRE  AS NOMBRE_SUBCATEGORIA,
                T.DESCRIPCION, T.MONTO, T.METODO_PAGO
        FROM    TRANSACCION  T
        INNER JOIN    SUBCATEGORIA S ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        INNER JOIN    CATEGORIA    C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   T.ID_PRESUPUESTO = P_ID_PRESUPUESTO
        AND     T.ANIO           = P_ANIO
        AND     T.MES            = P_MES
        ORDER   BY T.FECHA_TRANSACCION DESC;
END SP_LISTAR_TRANSACCIONES;
/

-- >> UPDATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_TRANSACCION (
    P_ID_TRANSACCION IN TRANSACCION.ID_TRANSACCION%TYPE,
    P_DESCRIPCION    IN TRANSACCION.DESCRIPCION%TYPE,
    P_MONTO          IN TRANSACCION.MONTO%TYPE,
    P_METODO_PAGO    IN TRANSACCION.METODO_PAGO%TYPE,
    P_NUM_FACTURA    IN TRANSACCION.NUM_FACTURA%TYPE,
    P_OBSERVACIONES  IN TRANSACCION.OBSERVACIONES%TYPE
) AS
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20150, 'El monto debe ser mayor a cero.');
    END IF;

    UPDATE TRANSACCION SET
        DESCRIPCION   = P_DESCRIPCION,
        MONTO         = P_MONTO,
        METODO_PAGO   = P_METODO_PAGO,
        NUM_FACTURA   = P_NUM_FACTURA,
        OBSERVACIONES = P_OBSERVACIONES
    WHERE ID_TRANSACCION = P_ID_TRANSACCION;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la transaccion: ' || P_ID_TRANSACCION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_TRANSACCION;
/

-- >> DELETE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_TRANSACCION (
    P_ID_TRANSACCION IN TRANSACCION.ID_TRANSACCION%TYPE
) AS
BEGIN
    -- Elimina primero la relacion con obligacion si existe
    DELETE FROM OBLIGACION_TRANSACCION WHERE ID_TRANSACCION = P_ID_TRANSACCION;
    DELETE FROM TRANSACCION            WHERE ID_TRANSACCION = P_ID_TRANSACCION;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la transaccion: ' || P_ID_TRANSACCION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_TRANSACCION;
/
