
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\procedimientos\crud_presupuesto_detalle.sql"

-- >> CREATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_DETALLE (
    P_ID_PRESUPUESTO  IN  PRESUPUESTO_DETALLE.ID_PRESUPUESTO%TYPE,
    P_ID_SUBCATEGORIA IN  PRESUPUESTO_DETALLE.ID_SUBCATEGORIA%TYPE,
    P_MONTO           IN  PRESUPUESTO_DETALLE.MONTO%TYPE,
    P_JUSTIFICACION   IN  PRESUPUESTO_DETALLE.JUSTIFICACION%TYPE,
    P_ID_GENERADO     OUT PRESUPUESTO_DETALLE.ID_DETALLE%TYPE
) AS
    V_ESTADO VARCHAR2(10);
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20140, 'El monto del detalle debe ser mayor a cero.');
    END IF;

    SELECT ESTADO_PRESUPUESTO INTO V_ESTADO
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;
    IF V_ESTADO != 'activo' THEN
        RAISE_APPLICATION_ERROR(-20141, 'Solo se pueden agregar detalles a presupuestos activos.');
    END IF;

    INSERT INTO PRESUPUESTO_DETALLE (
        ID_DETALLE, ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO, JUSTIFICACION
    ) VALUES (
        NULL, P_ID_PRESUPUESTO, P_ID_SUBCATEGORIA, P_MONTO, P_JUSTIFICACION
    ) RETURNING ID_DETALLE INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro el presupuesto: ' || P_ID_PRESUPUESTO);
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Esa subcategoria ya tiene un monto asignado en este presupuesto.');
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_DETALLE;
/

-- >> READ (todos)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_DETALLES (
    P_ID_PRESUPUESTO IN  PRESUPUESTO_DETALLE.ID_PRESUPUESTO%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  D.ID_DETALLE, D.ID_PRESUPUESTO, D.ID_SUBCATEGORIA,
                D.MONTO, D.JUSTIFICACION,
                S.NOMBRE  AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE  AS NOMBRE_CATEGORIA,
                C.TIPO
        FROM    PRESUPUESTO_DETALLE D
        JOIN    SUBCATEGORIA        S ON D.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA           C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   D.ID_PRESUPUESTO = P_ID_PRESUPUESTO
        ORDER   BY C.TIPO, C.NOMBRE, S.NOMBRE;
END SP_LISTAR_DETALLES;
/

-- >> UPDATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_DETALLE (
    P_ID_DETALLE    IN PRESUPUESTO_DETALLE.ID_DETALLE%TYPE,
    P_MONTO         IN PRESUPUESTO_DETALLE.MONTO%TYPE,
    P_JUSTIFICACION IN PRESUPUESTO_DETALLE.JUSTIFICACION%TYPE
) AS
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20140, 'El monto del detalle debe ser mayor a cero.');
    END IF;

    UPDATE PRESUPUESTO_DETALLE SET
        MONTO = P_MONTO, JUSTIFICACION = P_JUSTIFICACION
    WHERE ID_DETALLE = P_ID_DETALLE;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro el detalle: ' || P_ID_DETALLE);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_DETALLE;
/

-- >> DELETE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_DETALLE (
    P_ID_DETALLE IN PRESUPUESTO_DETALLE.ID_DETALLE%TYPE
) AS
BEGIN
    DELETE FROM PRESUPUESTO_DETALLE WHERE ID_DETALLE = P_ID_DETALLE;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro el detalle: ' || P_ID_DETALLE);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_DETALLE;
/
