
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\procedimientos\crud_presupuesto.sql"


-- >> CREATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRESUPUESTO (
    P_ID_USER            IN  PRESUPUESTO.ID_USER%TYPE,
    P_NOMBRE_DESCRIPTIVO IN  PRESUPUESTO.NOMBRE_DESCRIPTIVO%TYPE,
    P_ANIO_INICIO        IN  PRESUPUESTO.ANIO_INICIO%TYPE,
    P_MES_INICIO         IN  PRESUPUESTO.MES_INICIO%TYPE,
    P_ANIO_FIN           IN  PRESUPUESTO.ANIO_FIN%TYPE,
    P_MES_FIN            IN  PRESUPUESTO.MES_FIN%TYPE,
    P_ID_GENERADO        OUT PRESUPUESTO.ID_PRESUPUESTO%TYPE
) AS
BEGIN
    IF TRIM(P_NOMBRE_DESCRIPTIVO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20130, 'El nombre descriptivo es obligatorio.');
    END IF;
    IF P_ANIO_INICIO < 2000 OR P_ANIO_FIN < 2000 THEN
        RAISE_APPLICATION_ERROR(-20131, 'El anio debe ser mayor a 2000.');
    END IF;
    IF P_ANIO_FIN < P_ANIO_INICIO OR
      (P_ANIO_FIN = P_ANIO_INICIO AND P_MES_FIN < P_MES_INICIO) THEN
        RAISE_APPLICATION_ERROR(-20132, 'El periodo fin no puede ser anterior al inicio.');
    END IF;

    INSERT INTO PRESUPUESTO (
        ID_PRESUPUESTO, ID_USER, NOMBRE_DESCRIPTIVO,
        ANIO_INICIO, MES_INICIO, ANIO_FIN, MES_FIN,
        TOTAL_INGRESOS, TOTAL_GASTOS, TOTAL_AHORRO,
        FECHA_HORA_CREACION, ESTADO_PRESUPUESTO
    ) VALUES (
        NULL, P_ID_USER, P_NOMBRE_DESCRIPTIVO,
        P_ANIO_INICIO, P_MES_INICIO, P_ANIO_FIN, P_MES_FIN,
        0, 0, 0, SYSTIMESTAMP, 'activo'
    ) RETURNING ID_PRESUPUESTO INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_PRESUPUESTO;
/

-- >> READ (uno por ID)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_PRESUPUESTO (
    P_ID_PRESUPUESTO IN  PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;
END SP_CONSULTAR_PRESUPUESTO;
/

-- >> READ (todos)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_PRESUPUESTOS (
    P_ID_USER IN  PRESUPUESTO.ID_USER%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM PRESUPUESTO
        WHERE  ID_USER = P_ID_USER
        ORDER  BY ANIO_INICIO DESC, MES_INICIO DESC;
END SP_LISTAR_PRESUPUESTOS;
/

-- >> UPDATE (nombre)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRESUPUESTO (
    P_ID_PRESUPUESTO     IN PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_NOMBRE_DESCRIPTIVO IN PRESUPUESTO.NOMBRE_DESCRIPTIVO%TYPE
) AS
    V_ESTADO VARCHAR2(10);
BEGIN
    SELECT ESTADO_PRESUPUESTO INTO V_ESTADO
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    IF V_ESTADO = 'cerrado' THEN
        RAISE_APPLICATION_ERROR(-20133, 'No se puede modificar un presupuesto cerrado.');
    END IF;
    IF TRIM(P_NOMBRE_DESCRIPTIVO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20130, 'El nombre descriptivo es obligatorio.');
    END IF;

    UPDATE PRESUPUESTO SET NOMBRE_DESCRIPTIVO = P_NOMBRE_DESCRIPTIVO
    WHERE  ID_PRESUPUESTO = P_ID_PRESUPUESTO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro el presupuesto: ' || P_ID_PRESUPUESTO);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_PRESUPUESTO;
/

-- >> DELETE (cierre — cambia estado a cerrado, no se borra fisicamente)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CERRAR_PRESUPUESTO (
    P_ID_PRESUPUESTO IN PRESUPUESTO.ID_PRESUPUESTO%TYPE
) AS
    V_ESTADO VARCHAR2(10);
BEGIN
    SELECT ESTADO_PRESUPUESTO INTO V_ESTADO
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    IF V_ESTADO = 'cerrado' THEN
        RAISE_APPLICATION_ERROR(-20134, 'El presupuesto ya esta cerrado.');
    END IF;

    UPDATE PRESUPUESTO SET ESTADO_PRESUPUESTO = 'cerrado'
    WHERE  ID_PRESUPUESTO = P_ID_PRESUPUESTO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro el presupuesto: ' || P_ID_PRESUPUESTO);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_CERRAR_PRESUPUESTO;
/
