
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\procedimientos\crud_subcategoria.sql"


-- >> CREATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_SUBCATEGORIA (
    P_ID_CATEGORIA    IN  SUBCATEGORIA.ID_CATEGORIA%TYPE,
    P_NOMBRE          IN  SUBCATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION     IN  SUBCATEGORIA.DESCRIPCION%TYPE,
    P_ID_GENERADO     OUT SUBCATEGORIA.ID_SUBCATEGORIA%TYPE
) AS
    V_EXISTE NUMBER;
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20120, 'El nombre de la subcategoria es obligatorio.');
    END IF;

    SELECT COUNT(*) INTO V_EXISTE FROM CATEGORIA WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    IF V_EXISTE = 0 THEN
        RAISE_APPLICATION_ERROR(-20121, 'No existe la categoria: ' || P_ID_CATEGORIA);
    END IF;

    INSERT INTO SUBCATEGORIA (
        ID_SUBCATEGORIA, ID_CATEGORIA,
        NOMBRE, DESCRIPCION, ACTIVA, SUB_POR_DEFECTO
    ) VALUES (
        NULL, P_ID_CATEGORIA,
        P_NOMBRE, P_DESCRIPCION, 1, 0
    ) RETURNING ID_SUBCATEGORIA INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_SUBCATEGORIA;
/

-- >> READ (uno por ID)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN  SUBCATEGORIA.ID_SUBCATEGORIA%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT S.*, C.NOMBRE AS NOMBRE_CATEGORIA, C.TIPO
        FROM   SUBCATEGORIA S
        INNER JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
        WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
END SP_CONSULTAR_SUBCATEGORIA;
/

-- >> READ (todos activos por categoria)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_SUBCATEGORIAS (
    P_ID_CATEGORIA IN  SUBCATEGORIA.ID_CATEGORIA%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT S.*, C.NOMBRE AS NOMBRE_CATEGORIA, C.TIPO
        FROM   SUBCATEGORIA S
        INNER JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
        WHERE  S.ID_CATEGORIA = P_ID_CATEGORIA
        AND    S.ACTIVA = 1
        ORDER  BY S.SUB_POR_DEFECTO DESC, S.NOMBRE;
END SP_LISTAR_SUBCATEGORIAS;
/

-- >> UPDATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN SUBCATEGORIA.ID_SUBCATEGORIA%TYPE,
    P_NOMBRE          IN SUBCATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION     IN SUBCATEGORIA.DESCRIPCION%TYPE
) AS
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20120, 'El nombre de la subcategoria es obligatorio.');
    END IF;

    UPDATE SUBCATEGORIA SET
        NOMBRE      = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION
    WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la subcategoria: ' || P_ID_SUBCATEGORIA);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_SUBCATEGORIA;
/

-- >> DELETE (soft delete — no permitido si es la unica activa o tiene transacciones)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN SUBCATEGORIA.ID_SUBCATEGORIA%TYPE
) AS
    V_ID_CATEGORIA SUBCATEGORIA.ID_CATEGORIA%TYPE;
    V_ACTIVAS      NUMBER;
    V_TIENE_TRX    NUMBER;
BEGIN
    SELECT ID_CATEGORIA INTO V_ID_CATEGORIA
    FROM   SUBCATEGORIA WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    SELECT COUNT(*) INTO V_TIENE_TRX
    FROM   TRANSACCION WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
    IF V_TIENE_TRX > 0 THEN
        RAISE_APPLICATION_ERROR(-20122,
            'No se puede desactivar: tiene ' || V_TIENE_TRX || ' transaccion(es) asociada(s).');
    END IF;

    SELECT COUNT(*) INTO V_ACTIVAS
    FROM   SUBCATEGORIA WHERE ID_CATEGORIA = V_ID_CATEGORIA AND ACTIVA = 1;
    IF V_ACTIVAS <= 1 THEN
        RAISE_APPLICATION_ERROR(-20123,
            'No se puede desactivar: es la unica subcategoria activa de la categoria.');
    END IF;

    UPDATE SUBCATEGORIA SET ACTIVA = 0 WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la subcategoria: ' || P_ID_SUBCATEGORIA);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_SUBCATEGORIA;
/
