
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\procedimientos\crud_obligacion.sql"


-- >> CREATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_OBLIGACION (
    P_ID_USER         IN  OBLIGACION_FIJA.ID_USER%TYPE,
    P_ID_SUBCATEGORIA IN  OBLIGACION_FIJA.ID_SUBCATEGORIA%TYPE,
    P_NOMBRE          IN  OBLIGACION_FIJA.NOMBRE%TYPE,
    P_DESCRIPCION     IN  OBLIGACION_FIJA.DESCRIPCION%TYPE,
    P_MONTO           IN  OBLIGACION_FIJA.MONTO%TYPE,
    P_DIA             IN  OBLIGACION_FIJA.DIA%TYPE,
    P_FECHA_INICIO    IN  OBLIGACION_FIJA.FECHA_INICIO%TYPE,
    P_FECHA_FIN       IN  OBLIGACION_FIJA.FECHA_FIN%TYPE,
    P_ID_GENERADO     OUT OBLIGACION_FIJA.ID_OBLIGACION%TYPE
) AS
    V_TIPO VARCHAR2(10);
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20160, 'El nombre de la obligacion es obligatorio.');
    END IF;
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20161, 'El monto debe ser mayor a cero.');
    END IF;
    IF P_DIA NOT BETWEEN 1 AND 31 THEN
        RAISE_APPLICATION_ERROR(-20162, 'El dia de vencimiento debe estar entre 1 y 31.');
    END IF;
    IF P_FECHA_FIN IS NOT NULL AND P_FECHA_FIN <= P_FECHA_INICIO THEN
        RAISE_APPLICATION_ERROR(-20163, 'La fecha fin debe ser mayor a la fecha inicio.');
    END IF;

    -- Solo subcategorias de tipo gasto pueden tener obligaciones
    SELECT C.TIPO INTO V_TIPO
    FROM   SUBCATEGORIA S
    JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF V_TIPO != 'gasto' THEN
        RAISE_APPLICATION_ERROR(-20164, 'Las obligaciones fijas solo aplican a subcategorias de tipo gasto.');
    END IF;

    INSERT INTO OBLIGACION_FIJA (
        ID_OBLIGACION, ID_USER, ID_SUBCATEGORIA,
        NOMBRE, DESCRIPCION, MONTO,
        DIA, VIGENTE, FECHA_INICIO, FECHA_FIN
    ) VALUES (
        NULL, P_ID_USER, P_ID_SUBCATEGORIA,
        P_NOMBRE, P_DESCRIPCION, P_MONTO,
        P_DIA, 1, P_FECHA_INICIO, P_FECHA_FIN
    ) RETURNING ID_OBLIGACION INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la subcategoria: ' || P_ID_SUBCATEGORIA);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_OBLIGACION;
/

-- >> READ (uno)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_OBLIGACION (
    P_ID_OBLIGACION IN  OBLIGACION_FIJA.ID_OBLIGACION%TYPE,
    P_CURSOR        OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  O.*,
                S.NOMBRE AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE AS NOMBRE_CATEGORIA,
                FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION) AS DIAS_VENCIMIENTO
        FROM    OBLIGACION_FIJA O
        JOIN    SUBCATEGORIA    S ON O.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA       C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   O.ID_OBLIGACION = P_ID_OBLIGACION;
END SP_CONSULTAR_OBLIGACION;
/

-- >> READ (todos)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_OBLIGACIONES (
    P_ID_USER IN  OBLIGACION_FIJA.ID_USER%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  O.*,
                S.NOMBRE AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE AS NOMBRE_CATEGORIA,
                FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION) AS DIAS_VENCIMIENTO
        FROM    OBLIGACION_FIJA O
        JOIN    SUBCATEGORIA    S ON O.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA       C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   O.ID_USER  = P_ID_USER
        AND     O.VIGENTE  = 1
        ORDER   BY O.DIA;
END SP_LISTAR_OBLIGACIONES;
/

-- >> UPDATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_OBLIGACION (
    P_ID_OBLIGACION   IN OBLIGACION_FIJA.ID_OBLIGACION%TYPE,
    P_NOMBRE          IN OBLIGACION_FIJA.NOMBRE%TYPE,
    P_DESCRIPCION     IN OBLIGACION_FIJA.DESCRIPCION%TYPE,
    P_MONTO           IN OBLIGACION_FIJA.MONTO%TYPE,
    P_DIA             IN OBLIGACION_FIJA.DIA%TYPE
) AS
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20161, 'El monto debe ser mayor a cero.');
    END IF;
    IF P_DIA NOT BETWEEN 1 AND 31 THEN
        RAISE_APPLICATION_ERROR(-20162, 'El dia debe estar entre 1 y 31.');
    END IF;

    UPDATE OBLIGACION_FIJA SET
        NOMBRE      = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION,
        MONTO       = P_MONTO,
        DIA         = P_DIA
    WHERE ID_OBLIGACION = P_ID_OBLIGACION;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la obligacion: ' || P_ID_OBLIGACION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_OBLIGACION;
/

-- >> DELETE / soft delete
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_OBLIGACION (
    P_ID_OBLIGACION IN OBLIGACION_FIJA.ID_OBLIGACION%TYPE
) AS
BEGIN
    UPDATE OBLIGACION_FIJA SET VIGENTE = 0 WHERE ID_OBLIGACION = P_ID_OBLIGACION;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro la obligacion: ' || P_ID_OBLIGACION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_OBLIGACION;
/
