
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\procedimientos\crud_usuario.sql"


-- >> CREATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO (
    P_PRIMER_NOMBRE    IN  USUARIO.PRIMER_NOMBRE%TYPE,
    P_SEGUNDO_NOMBRE   IN  USUARIO.SEGUNDO_NOMBRE%TYPE,
    P_PRIMER_APELLIDO  IN  USUARIO.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO IN  USUARIO.SEGUNDO_APELLIDO%TYPE,
    P_CORREO           IN  USUARIO.CORREO%TYPE,
    P_PASSWORD         IN  USUARIO.PASSWORD%TYPE,
    P_SALARIO_BASE     IN  USUARIO.SALARIO_BASE%TYPE,
    P_ID_GENERADO      OUT USUARIO.ID_USER%TYPE
) AS
BEGIN
    IF TRIM(P_PRIMER_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'El primer nombre es obligatorio.');
    END IF;
    IF TRIM(P_PRIMER_APELLIDO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20101, 'El primer apellido es obligatorio.');
    END IF;
    IF TRIM(P_CORREO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20102, 'El correo es obligatorio.');
    END IF;
    IF TRIM(P_PASSWORD) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20103, 'La contrasena es obligatoria.');
    END IF;
    IF P_SALARIO_BASE < 0 THEN
        RAISE_APPLICATION_ERROR(-20104, 'El salario no puede ser negativo.');
    END IF;

    INSERT INTO USUARIO (
        ID_USER, PRIMER_NOMBRE, SEGUNDO_NOMBRE,
        PRIMER_APELLIDO, SEGUNDO_APELLIDO,
        CORREO, PASSWORD, FECHA_REGISTRO,
        SALARIO_BASE, ESTADO
    ) VALUES (
        NULL,
        P_PRIMER_NOMBRE, P_SEGUNDO_NOMBRE,
        P_PRIMER_APELLIDO, P_SEGUNDO_APELLIDO,
        P_CORREO, P_PASSWORD, SYSDATE,
        P_SALARIO_BASE, 1
    ) RETURNING ID_USER INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe un usuario con ese correo.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_USUARIO;
/

-- >> READ (uno por ID)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_USUARIO (
    P_ID_USER IN  USUARIO.ID_USER%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM USUARIO WHERE ID_USER = P_ID_USER;
END SP_CONSULTAR_USUARIO;
/

-- >> READ (todos)
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_USUARIOS (
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM USUARIO
        WHERE  ESTADO = 1
        ORDER  BY PRIMER_APELLIDO, PRIMER_NOMBRE;
END SP_LISTAR_USUARIOS;
/

-- >> UPDATE
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO (
    P_ID_USER          IN USUARIO.ID_USER%TYPE,
    P_PRIMER_NOMBRE    IN USUARIO.PRIMER_NOMBRE%TYPE,
    P_SEGUNDO_NOMBRE   IN USUARIO.SEGUNDO_NOMBRE%TYPE,
    P_PRIMER_APELLIDO  IN USUARIO.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO IN USUARIO.SEGUNDO_APELLIDO%TYPE,
    P_SALARIO_BASE     IN USUARIO.SALARIO_BASE%TYPE
) AS
BEGIN
    IF TRIM(P_PRIMER_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'El primer nombre es obligatorio.');
    END IF;
    IF P_SALARIO_BASE < 0 THEN
        RAISE_APPLICATION_ERROR(-20104, 'El salario no puede ser negativo.');
    END IF;

    UPDATE USUARIO SET
        PRIMER_NOMBRE    = P_PRIMER_NOMBRE,
        SEGUNDO_NOMBRE   = P_SEGUNDO_NOMBRE,
        PRIMER_APELLIDO  = P_PRIMER_APELLIDO,
        SEGUNDO_APELLIDO = P_SEGUNDO_APELLIDO,
        SALARIO_BASE     = P_SALARIO_BASE
    WHERE ID_USER = P_ID_USER;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro el usuario: ' || P_ID_USER);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_USUARIO;
/

-- >> DELETE / softdelete
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_USUARIO (
    P_ID_USER IN USUARIO.ID_USER%TYPE
) AS
BEGIN
    UPDATE USUARIO SET ESTADO = 0 WHERE ID_USER = P_ID_USER;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontro el usuario: ' || P_ID_USER);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_USUARIO;
/
