// Steve Valladares - 22341344
// Screaming Snake

TABLE USUARIO {
  ID_USER varchar(10) [primary key]
  PRIMER_NOMBRE varchar(30)
  SEGUNDO_NOMBRE varchar(30)
  PRIMER_APELLIDO varchar(30)
  SEGUNDO_APELLIDO varchar(30)
  CORREO varchar(100) [unique]
  PASSWORD varchar(50)
  FECHA_REGISTRO date
  SALARIO_BASE decimal(10,2)
  ESTADO bool
}

TABLE PRESUPUESTO {
  ID_PRESUPUESTO varchar(10) [primary key]
  ID_USER varchar(10)
  NOMBRE_DESCRIPTIVO varchar(40)
  ANIO_INICIO int
  MES_INICIO int
  ANIO_FIN int
  MES_FIN int
  TOTAL_INGRESOS decimal(10,2)
  TOTAL_GASTOS decimal(10,2)
  TOTAL_AHORRO decimal(10,2)
  FECHA_HORA_CREACION timestamp
  ESTADO_PRESUPUESTO varchar(10)
}

TABLE CATEGORIA {
  ID_CATEGORIA varchar(10) [primary key]
  NOMBRE varchar(15)
  DESCRIPCION varchar(60)
  TIPO varchar(10)
  NOMBRE_ICON_UI varchar(20)
  COLOR_HEX varchar(20)
  ORDEN int
}

TABLE SUBCATEGORIA {
  ID_SUBCATEGORIA varchar(10) [primary key]
  ID_CATEGORIA varchar(10)
  NOMBRE varchar(15)
  DESCRIPCION varchar(60)
  ACTIVA bool
  SUB_POR_DEFECTO bool
}

TABLE PRESUPUESTO_DETALLE {
  ID_DETALLE varchar(10) [primary key]
  ID_PRESUPUESTO varchar(10)
  ID_SUBCATEGORIA varchar(10)
  MONTO decimal(10,2)
  JUSTIFICACION varchar(60)
}

TABLE OBLIGACION_FIJA {
  ID_OBLIGACION varchar(10) [primary key]
  ID_USER varchar(10)
  ID_SUBCATEGORIA varchar(10)
  NOMBRE varchar(20)
  DESCRIPCION varchar(60)
  MONTO decimal(10,2)
  DIA int
  VIGENTE bool
  FECHA_INICIO date
  FECHA_FIN date
}

TABLE TRANSACCION {
  ID_TRANSACCION varchar(10) [primary key]
  ID_DETALLE varchar(10) // FK
  ID_USER varchar(10)
  ID_PRESUPUESTO varchar(10)
  ANIO int
  MES int
  ID_SUBCATEGORIA varchar(10)
  TIPO varchar(15)
  DESCRIPCION varchar(60)
  MONTO decimal(10,2)
  FECHA_TRANSACCION date
  METODO_PAGO varchar(20)
  NUM_FACTURA int
  OBSERVACIONES varchar(60)
  FECHA_HORA_REGISTRO timestamp
}

// TABLA RELACION
TABLE OBLIGACION_TRANSACCION {
  ID_TRANSACCION varchar(10) [primary key] // FK
  ID_OBLIGACION varchar(10) // FK
}

REF: "USUARIO"."ID_USER" < "PRESUPUESTO"."ID_USER"
REF: "PRESUPUESTO"."ID_PRESUPUESTO" < "PRESUPUESTO_DETALLE"."ID_PRESUPUESTO"
REF: "SUBCATEGORIA"."ID_SUBCATEGORIA" < "PRESUPUESTO_DETALLE"."ID_SUBCATEGORIA"
REF: "PRESUPUESTO_DETALLE"."ID_DETALLE" < "TRANSACCION"."ID_DETALLE"
REF: "CATEGORIA"."ID_CATEGORIA" < "SUBCATEGORIA"."ID_CATEGORIA"
REF: "SUBCATEGORIA"."ID_SUBCATEGORIA" < "OBLIGACION_FIJA"."ID_SUBCATEGORIA"
REF: "TRANSACCION"."ID_TRANSACCION" < "OBLIGACION_TRANSACCION"."ID_TRANSACCION"
REF: "OBLIGACION_FIJA"."ID_OBLIGACION" < "OBLIGACION_TRANSACCION"."ID_OBLIGACION"
