-- ============================================================
-- SISTEMA DE PRESUPUESTO PERSONAL
-- Steve Valladares - 22341344
-- ============================================================

--sqlplus system/OracleTBD@localhost:1521/XE @"C:\Users\EzTiB\TBD1_Proyecto\SQL\DDL_tablas.sql"

-- TABLA: USUARIO
CREATE TABLE USUARIO (
    ID_USER           VARCHAR2(10)   PRIMARY KEY,
    PRIMER_NOMBRE     VARCHAR2(30)   NOT NULL,
    SEGUNDO_NOMBRE    VARCHAR2(30),
    PRIMER_APELLIDO   VARCHAR2(30)   NOT NULL,
    SEGUNDO_APELLIDO  VARCHAR2(30),
    CORREO            VARCHAR2(100)  NOT NULL UNIQUE,
    PASSWORD          VARCHAR2(50)   NOT NULL,
    FECHA_REGISTRO    DATE           DEFAULT SYSDATE,
    SALARIO_BASE      DECIMAL(10,2)  DEFAULT 0,
    ESTADO            NUMBER(1)      DEFAULT 1 CHECK (ESTADO IN (0,1))
); 

-- TABLA: PRESUPUESTO
CREATE TABLE PRESUPUESTO (
    ID_PRESUPUESTO       VARCHAR2(10)   PRIMARY KEY,
    ID_USER              VARCHAR2(10)   NOT NULL REFERENCES USUARIO(ID_USER),
    NOMBRE_DESCRIPTIVO   VARCHAR2(40)   NOT NULL,
    ANIO_INICIO          NUMBER(4)      NOT NULL,
    MES_INICIO           NUMBER(2)      NOT NULL CHECK (MES_INICIO BETWEEN 1 AND 12),
    ANIO_FIN             NUMBER(4)      NOT NULL,
    MES_FIN              NUMBER(2)      NOT NULL CHECK (MES_FIN BETWEEN 1 AND 12),
    TOTAL_INGRESOS       DECIMAL(10,2)  DEFAULT 0,
    TOTAL_GASTOS         DECIMAL(10,2)  DEFAULT 0,
    TOTAL_AHORRO         DECIMAL(10,2)  DEFAULT 0,
    FECHA_HORA_CREACION  TIMESTAMP      DEFAULT SYSTIMESTAMP,
    ESTADO_PRESUPUESTO   VARCHAR2(10)   DEFAULT 'activo'
                         CHECK (ESTADO_PRESUPUESTO IN ('activo','cerrado','borrador')),
    CONSTRAINT CHK_PERIODO CHECK (
        ANIO_FIN > ANIO_INICIO OR
        (ANIO_FIN = ANIO_INICIO AND MES_FIN >= MES_INICIO)
    )
);

-- TABLA: CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA    VARCHAR2(10)  PRIMARY KEY,
    NOMBRE          VARCHAR2(50)  NOT NULL,
    DESCRIPCION     VARCHAR2(100),
    TIPO            VARCHAR2(10)  NOT NULL CHECK (TIPO IN ('ingreso','gasto','ahorro')),
    NOMBRE_ICON_UI  VARCHAR2(20),
    COLOR_HEX       VARCHAR2(7),
    ORDEN           NUMBER        DEFAULT 0
);


-- TABLA: SUBCATEGORIA
CREATE TABLE SUBCATEGORIA (
    ID_SUBCATEGORIA  VARCHAR2(10)  PRIMARY KEY,
    ID_CATEGORIA     VARCHAR2(10)  NOT NULL REFERENCES CATEGORIA(ID_CATEGORIA),
    NOMBRE           VARCHAR2(50)  NOT NULL,
    DESCRIPCION      VARCHAR2(100),
    ACTIVA           NUMBER(1)     DEFAULT 1 CHECK (ACTIVA IN (0,1)),
    SUB_POR_DEFECTO  NUMBER(1)     DEFAULT 0 CHECK (SUB_POR_DEFECTO IN (0,1))
);


-- TABLA: PRESUPUESTO_DETALLE
CREATE TABLE PRESUPUESTO_DETALLE (
    ID_DETALLE       VARCHAR2(10)   PRIMARY KEY,
    ID_PRESUPUESTO   VARCHAR2(10)   NOT NULL REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
    ID_SUBCATEGORIA  VARCHAR2(10)   NOT NULL REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
    MONTO            DECIMAL(10,2)  NOT NULL,
    JUSTIFICACION    VARCHAR2(100),
    CONSTRAINT UQ_DETALLE UNIQUE (ID_PRESUPUESTO, ID_SUBCATEGORIA)
);


-- TABLA: OBLIGACION_FIJA
CREATE TABLE OBLIGACION_FIJA (
    ID_OBLIGACION    VARCHAR2(10)   PRIMARY KEY,
    ID_USER          VARCHAR2(10)   NOT NULL REFERENCES USUARIO(ID_USER),
    ID_SUBCATEGORIA  VARCHAR2(10)   NOT NULL REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
    NOMBRE           VARCHAR2(50)   NOT NULL,
    DESCRIPCION      VARCHAR2(100),
    MONTO            DECIMAL(10,2)  NOT NULL,
    DIA              NUMBER(2)      NOT NULL CHECK (DIA BETWEEN 1 AND 31),
    VIGENTE          NUMBER(1)      DEFAULT 1 CHECK (VIGENTE IN (0,1)),
    FECHA_INICIO     DATE           NOT NULL,
    FECHA_FIN        DATE,
    CONSTRAINT CHK_FECHAS_OBLIGACION CHECK (FECHA_FIN IS NULL OR FECHA_FIN > FECHA_INICIO)
);


-- TABLA: TRANSACCION
CREATE TABLE TRANSACCION (
    ID_TRANSACCION       VARCHAR2(10)   PRIMARY KEY,
    ID_USER              VARCHAR2(10)   NOT NULL REFERENCES USUARIO(ID_USER),
    ID_PRESUPUESTO       VARCHAR2(10)   NOT NULL REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
    ID_SUBCATEGORIA      VARCHAR2(10)   NOT NULL REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
    ANIO                 NUMBER(4)      NOT NULL,
    MES                  NUMBER(2)      NOT NULL CHECK (MES BETWEEN 1 AND 12),
    TIPO                 VARCHAR2(15)   NOT NULL CHECK (TIPO IN ('ingreso','gasto','ahorro')),
    DESCRIPCION          VARCHAR2(100)  NOT NULL,
    MONTO                DECIMAL(10,2)  NOT NULL,
    FECHA_TRANSACCION    DATE           NOT NULL,
    METODO_PAGO          VARCHAR2(20)   DEFAULT 'efectivo'
                         CHECK (METODO_PAGO IN ('efectivo','tarjeta_debito','tarjeta_credito','transferencia')),
    NUM_FACTURA          VARCHAR2(20),
    OBSERVACIONES        VARCHAR2(100),
    FECHA_HORA_REGISTRO  TIMESTAMP      DEFAULT SYSTIMESTAMP
);


-- TABLA: OBLIGACION_TRANSACCION
-- Tabla relación entre Obligacion y Transaccion
CREATE TABLE OBLIGACION_TRANSACCION (
    ID_TRANSACCION  VARCHAR2(10)  PRIMARY KEY REFERENCES TRANSACCION(ID_TRANSACCION),
    ID_OBLIGACION   VARCHAR2(10)  NOT NULL    REFERENCES OBLIGACION_FIJA(ID_OBLIGACION)
);

-- INDICES
CREATE INDEX IDX_TRANSACCION_PERIODO  ON TRANSACCION(ANIO, MES);
CREATE INDEX IDX_TRANSACCION_SUBCAT   ON TRANSACCION(ID_SUBCATEGORIA);
CREATE INDEX IDX_TRANSACCION_PRESUP   ON TRANSACCION(ID_PRESUPUESTO);
CREATE INDEX IDX_SUBCATEGORIA_CAT     ON SUBCATEGORIA(ID_CATEGORIA);
CREATE INDEX IDX_PRESUPUESTO_USER     ON PRESUPUESTO(ID_USER);
