
-- sqlplus system/OracleTBD@localhost:1521/XE @"C:\Users\EzTiB\source\repos\TBD1_Proyecto\TBD1_Proyecto\SQL\funciones.sql"


CREATE OR REPLACE FUNCTION FN_CALCULAR_MONTO_EJECUTADO (
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_MES             IN NUMBER
) RETURN NUMBER AS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT NVL(SUM(MONTO), 0)
    INTO   V_TOTAL
    FROM   TRANSACCION
    WHERE  ID_SUBCATEGORIA = P_ID_SUBCATEGORIA
    AND    ANIO            = P_ANIO
    AND    MES             = P_MES;
    RETURN V_TOTAL;
END FN_CALCULAR_MONTO_EJECUTADO;
/

CREATE OR REPLACE FUNCTION FN_CALCULAR_PORCENTAJE_EJECUTADO (
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_ID_PRESUPUESTO  IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_MES             IN NUMBER
) RETURN NUMBER AS
    V_PRESUPUESTADO NUMBER := 0;
    V_EJECUTADO     NUMBER := 0;
BEGIN
    SELECT NVL(MONTO, 0)
    INTO   V_PRESUPUESTADO
    FROM   PRESUPUESTO_DETALLE
    WHERE  ID_PRESUPUESTO  = P_ID_PRESUPUESTO
    AND    ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    V_EJECUTADO := FN_CALCULAR_MONTO_EJECUTADO(P_ID_SUBCATEGORIA, P_ANIO, P_MES);

    IF V_PRESUPUESTADO = 0 THEN RETURN 0; END IF;
    RETURN ROUND((V_EJECUTADO / V_PRESUPUESTADO) * 100, 2);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_CALCULAR_PORCENTAJE_EJECUTADO;
/

CREATE OR REPLACE FUNCTION FN_OBTENER_BALANCE_SUBCATEGORIA (
    P_ID_PRESUPUESTO  IN VARCHAR2,
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_MES             IN NUMBER
) RETURN NUMBER AS
    V_PRESUPUESTADO NUMBER := 0;
    V_EJECUTADO     NUMBER := 0;
BEGIN
    SELECT NVL(MONTO, 0)
    INTO   V_PRESUPUESTADO
    FROM   PRESUPUESTO_DETALLE
    WHERE  ID_PRESUPUESTO  = P_ID_PRESUPUESTO
    AND    ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    V_EJECUTADO := FN_CALCULAR_MONTO_EJECUTADO(P_ID_SUBCATEGORIA, P_ANIO, P_MES);
    RETURN V_PRESUPUESTADO - V_EJECUTADO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_OBTENER_BALANCE_SUBCATEGORIA;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_EJECUTADO_CATEGORIA (
    P_ID_CATEGORIA IN VARCHAR2,
    P_ANIO         IN NUMBER,
    P_MES          IN NUMBER
) RETURN NUMBER AS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT NVL(SUM(T.MONTO), 0)
    INTO   V_TOTAL
    FROM   TRANSACCION  T
    JOIN   SUBCATEGORIA S ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
    WHERE  S.ID_CATEGORIA = P_ID_CATEGORIA
    AND    T.ANIO         = P_ANIO
    AND    T.MES          = P_MES;
    RETURN V_TOTAL;
END FN_TOTAL_EJECUTADO_CATEGORIA;
/

CREATE OR REPLACE FUNCTION FN_DIAS_HASTA_VENCIMIENTO (
    P_ID_OBLIGACION IN VARCHAR2
) RETURN NUMBER AS
    V_DIA   NUMBER;
    V_FECHA DATE;
BEGIN
    SELECT DIA INTO V_DIA
    FROM OBLIGACION_FIJA WHERE ID_OBLIGACION = P_ID_OBLIGACION;

    V_FECHA := TRUNC(SYSDATE, 'MM') + V_DIA - 1;
    IF V_FECHA < TRUNC(SYSDATE) THEN
        V_FECHA := ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1) + V_DIA - 1;
    END IF;
    RETURN TRUNC(V_FECHA) - TRUNC(SYSDATE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN -1;
END FN_DIAS_HASTA_VENCIMIENTO;
/

CREATE OR REPLACE FUNCTION FN_VALIDAR_VIGENCIA (
    P_ANIO           IN NUMBER,
    P_MES            IN NUMBER,
    P_ID_PRESUPUESTO IN VARCHAR2
) RETURN NUMBER AS
    V_INICIO NUMBER;
    V_FIN    NUMBER;
    V_FECHA  NUMBER;
BEGIN
    SELECT (ANIO_INICIO * 100 + MES_INICIO),
           (ANIO_FIN    * 100 + MES_FIN)
    INTO   V_INICIO, V_FIN
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    V_FECHA := P_ANIO * 100 + P_MES;
    IF V_FECHA BETWEEN V_INICIO AND V_FIN THEN RETURN 1;
    ELSE RETURN 0;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_VALIDAR_VIGENCIA;
/
