
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\funciones\funciones.sql"


CREATE OR REPLACE FUNCTION FN_CALCULAR_MONTO_EJECUTADO (
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_MES             IN NUMBER
) RETURN NUMBER AS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT NVL(SUM(MONTO), 0)
    INTO   V_TOTAL
    FROM   TRANSACCION
    WHERE  ID_SUBCATEGORIA = P_ID_SUBCATEGORIA
    AND    ANIO            = P_ANIO
    AND    MES             = P_MES;
    RETURN V_TOTAL;
END FN_CALCULAR_MONTO_EJECUTADO;
/



CREATE OR REPLACE FUNCTION FN_CALCULAR_PORCENTAJE_EJECUTADO (
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_ID_PRESUPUESTO  IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_MES             IN NUMBER
) RETURN NUMBER AS
    V_PRESUPUESTADO NUMBER := 0;
    V_EJECUTADO     NUMBER := 0;
BEGIN
    SELECT NVL(MONTO, 0)
    INTO   V_PRESUPUESTADO
    FROM   PRESUPUESTO_DETALLE
    WHERE  ID_PRESUPUESTO  = P_ID_PRESUPUESTO
    AND    ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    V_EJECUTADO := FN_CALCULAR_MONTO_EJECUTADO(P_ID_SUBCATEGORIA, P_ANIO, P_MES);

    IF V_PRESUPUESTADO = 0 THEN RETURN 0; END IF;
    RETURN ROUND((V_EJECUTADO / V_PRESUPUESTADO) * 100, 2);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_CALCULAR_PORCENTAJE_EJECUTADO;
/


CREATE OR REPLACE FUNCTION FN_OBTENER_BALANCE_SUBCATEGORIA (
    P_ID_PRESUPUESTO  IN VARCHAR2,
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_MES             IN NUMBER
) RETURN NUMBER AS
    V_PRESUPUESTADO NUMBER := 0;
    V_EJECUTADO     NUMBER := 0;
BEGIN
    SELECT NVL(MONTO, 0)
    INTO   V_PRESUPUESTADO
    FROM   PRESUPUESTO_DETALLE
    WHERE  ID_PRESUPUESTO  = P_ID_PRESUPUESTO
    AND    ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    V_EJECUTADO := FN_CALCULAR_MONTO_EJECUTADO(P_ID_SUBCATEGORIA, P_ANIO, P_MES);
    RETURN V_PRESUPUESTADO - V_EJECUTADO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_OBTENER_BALANCE_SUBCATEGORIA;
/


CREATE OR REPLACE FUNCTION FN_OBTENER_TOTAL_CATEGORIA_MES (
    P_ID_CATEGORIA   IN VARCHAR2,
    P_ID_PRESUPUESTO IN VARCHAR2
) RETURN NUMBER AS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT NVL(SUM(D.MONTO), 0)
    INTO   V_TOTAL
    FROM   PRESUPUESTO_DETALLE D
    INNER JOIN   SUBCATEGORIA        S ON D.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
    WHERE  S.ID_CATEGORIA    = P_ID_CATEGORIA
    AND    D.ID_PRESUPUESTO  = P_ID_PRESUPUESTO;
    RETURN V_TOTAL;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_OBTENER_TOTAL_CATEGORIA_MES;
/


CREATE OR REPLACE FUNCTION FN_TOTAL_EJECUTADO_CATEGORIA (
    P_ID_CATEGORIA IN VARCHAR2,
    P_ANIO         IN NUMBER,
    P_MES          IN NUMBER
) RETURN NUMBER AS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT NVL(SUM(T.MONTO), 0)
    INTO   V_TOTAL
    FROM   TRANSACCION  T
    INNER JOIN   SUBCATEGORIA S ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
    WHERE  S.ID_CATEGORIA = P_ID_CATEGORIA
    AND    T.ANIO         = P_ANIO
    AND    T.MES          = P_MES;
    RETURN V_TOTAL;
END FN_TOTAL_EJECUTADO_CATEGORIA;
/


CREATE OR REPLACE FUNCTION FN_DIAS_HASTA_VENCIMIENTO (
    P_ID_OBLIGACION IN VARCHAR2
) RETURN NUMBER AS
    V_DIA   NUMBER;
    V_FECHA DATE;
BEGIN
    SELECT DIA INTO V_DIA
    FROM   OBLIGACION_FIJA WHERE ID_OBLIGACION = P_ID_OBLIGACION;

    V_FECHA := TRUNC(SYSDATE, 'MM') + V_DIA - 1;
    IF V_FECHA < TRUNC(SYSDATE) THEN
        V_FECHA := ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1) + V_DIA - 1;
    END IF;
    RETURN TRUNC(V_FECHA) - TRUNC(SYSDATE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN -1;
END FN_DIAS_HASTA_VENCIMIENTO;
/


CREATE OR REPLACE FUNCTION FN_VALIDAR_VIGENCIA (
    P_ANIO           IN NUMBER,
    P_MES            IN NUMBER,
    P_ID_PRESUPUESTO IN VARCHAR2
) RETURN NUMBER AS
    V_INICIO NUMBER;
    V_FIN    NUMBER;
    V_FECHA  NUMBER;
BEGIN
    SELECT (ANIO_INICIO * 100 + MES_INICIO),
           (ANIO_FIN    * 100 + MES_FIN)
    INTO   V_INICIO, V_FIN
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    V_FECHA := P_ANIO * 100 + P_MES;
    IF V_FECHA BETWEEN V_INICIO AND V_FIN THEN RETURN 1;
    ELSE RETURN 0;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_VALIDAR_VIGENCIA;
/


CREATE OR REPLACE FUNCTION FN_OBTENER_CATEGORIA_POR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN VARCHAR2
) RETURN VARCHAR2 AS
    V_ID_CATEGORIA VARCHAR2(10);
BEGIN
    SELECT ID_CATEGORIA INTO V_ID_CATEGORIA
    FROM   SUBCATEGORIA WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
    RETURN V_ID_CATEGORIA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
END FN_OBTENER_CATEGORIA_POR_SUBCATEGORIA;
/


CREATE OR REPLACE FUNCTION FN_CALCULAR_PROYECCION_GASTO_MENSUAL (
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_MES             IN NUMBER
) RETURN NUMBER AS
    V_EJECUTADO        NUMBER := 0;
    V_DIAS_TRANSCURRIDOS NUMBER;
    V_DIAS_MES         NUMBER;
    V_HOY              DATE := TRUNC(SYSDATE);
    V_INICIO_MES       DATE;
    V_FIN_MES          DATE;
BEGIN
    V_INICIO_MES := TO_DATE(P_ANIO || '-' || LPAD(P_MES, 2, '0') || '-01', 'YYYY-MM-DD');
    V_FIN_MES    := LAST_DAY(V_INICIO_MES);
    V_DIAS_MES   := V_FIN_MES - V_INICIO_MES + 1;

    -- Si el mes ya terminó, usar todos los días
    IF V_HOY >= V_FIN_MES THEN
        V_DIAS_TRANSCURRIDOS := V_DIAS_MES;
    ELSE
        V_DIAS_TRANSCURRIDOS := V_HOY - V_INICIO_MES + 1;
    END IF;

    V_EJECUTADO := FN_CALCULAR_MONTO_EJECUTADO(P_ID_SUBCATEGORIA, P_ANIO, P_MES);

    IF V_DIAS_TRANSCURRIDOS = 0 THEN RETURN 0; END IF;
    RETURN ROUND((V_EJECUTADO / V_DIAS_TRANSCURRIDOS) * V_DIAS_MES, 2);
END FN_CALCULAR_PROYECCION_GASTO_MENSUAL;
/


CREATE OR REPLACE FUNCTION FN_OBTENER_PROMEDIO_GASTO_SUBCATEGORIA (
    P_ID_USER         IN VARCHAR2,
    P_ID_SUBCATEGORIA IN VARCHAR2,
    P_CANTIDAD_MESES  IN NUMBER
) RETURN NUMBER AS
    V_PROMEDIO NUMBER := 0;
    V_FECHA_LIMITE DATE;
BEGIN
    V_FECHA_LIMITE := ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -P_CANTIDAD_MESES);

    SELECT NVL(AVG(TOTAL_MES), 0)
    INTO   V_PROMEDIO
    FROM (
        SELECT SUM(T.MONTO) AS TOTAL_MES
        FROM   TRANSACCION T
        WHERE  T.ID_USER          = P_ID_USER
        AND    T.ID_SUBCATEGORIA  = P_ID_SUBCATEGORIA
        AND    TO_DATE(T.ANIO || '-' || LPAD(T.MES, 2, '0') || '-01', 'YYYY-MM-DD') >= V_FECHA_LIMITE
        GROUP  BY T.ANIO, T.MES
    );

    RETURN ROUND(V_PROMEDIO, 2);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END FN_OBTENER_PROMEDIO_GASTO_SUBCATEGORIA;
/
