
-- sqlplus system/OracleTBD@localhost:1521/XE @"...\database\procedimientos\procedures_negocio.sql"



CREATE OR REPLACE PROCEDURE SP_CALCULAR_BALANCE_MENSUAL (
    P_ID_USER         IN  TRANSACCION.ID_USER%TYPE,
    P_ID_PRESUPUESTO  IN  TRANSACCION.ID_PRESUPUESTO%TYPE,
    P_ANIO            IN  TRANSACCION.ANIO%TYPE,
    P_MES             IN  TRANSACCION.MES%TYPE,
    P_TOTAL_INGRESOS  OUT NUMBER,
    P_TOTAL_GASTOS    OUT NUMBER,
    P_TOTAL_AHORROS   OUT NUMBER,
    P_BALANCE_FINAL   OUT NUMBER
) AS
BEGIN
    SELECT
        NVL(SUM(CASE WHEN TIPO = 'ingreso' THEN MONTO ELSE 0 END), 0),
        NVL(SUM(CASE WHEN TIPO = 'gasto'   THEN MONTO ELSE 0 END), 0),
        NVL(SUM(CASE WHEN TIPO = 'ahorro'  THEN MONTO ELSE 0 END), 0)
    INTO
        P_TOTAL_INGRESOS,
        P_TOTAL_GASTOS,
        P_TOTAL_AHORROS
    FROM TRANSACCION
    WHERE ID_USER        = P_ID_USER
    AND   ID_PRESUPUESTO = P_ID_PRESUPUESTO
    AND   ANIO           = P_ANIO
    AND   MES            = P_MES;

    P_BALANCE_FINAL := P_TOTAL_INGRESOS - P_TOTAL_GASTOS - P_TOTAL_AHORROS;
EXCEPTION
    WHEN OTHERS THEN RAISE;
END SP_CALCULAR_BALANCE_MENSUAL;
/


CREATE OR REPLACE PROCEDURE SP_PROCESAR_OBLIGACIONES_MES (
    P_ID_USER        IN  OBLIGACION_FIJA.ID_USER%TYPE,
    P_ANIO           IN  NUMBER,
    P_MES            IN  NUMBER,
    P_ID_PRESUPUESTO IN  PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            O.ID_OBLIGACION,
            O.NOMBRE,
            O.MONTO,
            O.DIA,
            S.NOMBRE  AS NOMBRE_SUBCATEGORIA,
            C.NOMBRE  AS NOMBRE_CATEGORIA,
            FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION) AS DIAS_VENCIMIENTO,
            -- Verifica si ya fue pagada este mes (existe transaccion vinculada)
            CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM   OBLIGACION_TRANSACCION OT
                    INNER JOIN   TRANSACCION            T  ON OT.ID_TRANSACCION = T.ID_TRANSACCION
                    WHERE  OT.ID_OBLIGACION  = O.ID_OBLIGACION
                    AND    T.ANIO            = P_ANIO
                    AND    T.MES             = P_MES
                ) THEN 1
                ELSE 0
            END AS YA_PAGADA
        FROM   OBLIGACION_FIJA O
        INNER JOIN   SUBCATEGORIA    S ON O.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        INNER JOIN   CATEGORIA       C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE  O.ID_USER = P_ID_USER
        AND    O.VIGENTE = 1
        ORDER  BY O.DIA;
END SP_PROCESAR_OBLIGACIONES_MES;
/


CREATE OR REPLACE PROCEDURE SP_OBTENER_RESUMEN_CATEGORIA_MES (
    P_ID_CATEGORIA        IN  CATEGORIA.ID_CATEGORIA%TYPE,
    P_ID_PRESUPUESTO      IN  PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_ANIO                IN  NUMBER,
    P_MES                 IN  NUMBER,
    P_MONTO_PRESUPUESTADO OUT NUMBER,
    P_MONTO_EJECUTADO     OUT NUMBER,
    P_PORCENTAJE          OUT NUMBER
) AS
BEGIN
    -- Total presupuestado
    SELECT NVL(SUM(D.MONTO), 0)
    INTO   P_MONTO_PRESUPUESTADO
    FROM   PRESUPUESTO_DETALLE D
    INNER JOIN   SUBCATEGORIA        S ON D.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
    WHERE  S.ID_CATEGORIA   = P_ID_CATEGORIA
    AND    D.ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    -- Total ejecutado
    P_MONTO_EJECUTADO := FN_TOTAL_EJECUTADO_CATEGORIA(P_ID_CATEGORIA, P_ANIO, P_MES);

    -- Porcentaje
    IF P_MONTO_PRESUPUESTADO = 0 THEN
        P_PORCENTAJE := 0;
    ELSE
        P_PORCENTAJE := ROUND((P_MONTO_EJECUTADO / P_MONTO_PRESUPUESTADO) * 100, 2);
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_MONTO_PRESUPUESTADO := 0;
        P_MONTO_EJECUTADO     := 0;
        P_PORCENTAJE          := 0;
    WHEN OTHERS THEN RAISE;
END SP_OBTENER_RESUMEN_CATEGORIA_MES;
/


CREATE OR REPLACE PROCEDURE SP_CALCULAR_MONTO_EJECUTADO_MES (
    P_ID_SUBCATEGORIA IN  TRANSACCION.ID_SUBCATEGORIA%TYPE,
    P_ID_PRESUPUESTO  IN  PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_ANIO            IN  NUMBER,
    P_MES             IN  NUMBER,
    P_MONTO_EJECUTADO OUT NUMBER
) AS
BEGIN
    P_MONTO_EJECUTADO := FN_CALCULAR_MONTO_EJECUTADO(P_ID_SUBCATEGORIA, P_ANIO, P_MES);
END SP_CALCULAR_MONTO_EJECUTADO_MES;
/


CREATE OR REPLACE PROCEDURE SP_CALCULAR_PORCENTAJE_EJECUCION_MES (
    P_ID_SUBCATEGORIA IN  TRANSACCION.ID_SUBCATEGORIA%TYPE,
    P_ID_PRESUPUESTO  IN  PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_ANIO            IN  NUMBER,
    P_MES             IN  NUMBER,
    P_PORCENTAJE      OUT NUMBER
) AS
BEGIN
    P_PORCENTAJE := FN_CALCULAR_PORCENTAJE_EJECUTADO(
        P_ID_SUBCATEGORIA, P_ID_PRESUPUESTO, P_ANIO, P_MES
    );
END SP_CALCULAR_PORCENTAJE_EJECUCION_MES;
/


CREATE OR REPLACE PROCEDURE SP_RESUMEN_PRESUPUESTO_MES (
    P_ID_PRESUPUESTO IN  PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_ANIO           IN  NUMBER,
    P_MES            IN  NUMBER,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            C.ID_CATEGORIA,
            C.NOMBRE           AS NOMBRE_CATEGORIA,
            C.TIPO,
            C.COLOR_HEX,
            C.NOMBRE_ICON_UI,
            S.ID_SUBCATEGORIA,
            S.NOMBRE           AS NOMBRE_SUBCATEGORIA,
            NVL(D.MONTO, 0)    AS MONTO_PRESUPUESTADO,
            FN_CALCULAR_MONTO_EJECUTADO(S.ID_SUBCATEGORIA, P_ANIO, P_MES)  AS MONTO_EJECUTADO,
            FN_OBTENER_BALANCE_SUBCATEGORIA(P_ID_PRESUPUESTO, S.ID_SUBCATEGORIA, P_ANIO, P_MES) AS BALANCE,
            FN_CALCULAR_PORCENTAJE_EJECUTADO(S.ID_SUBCATEGORIA, P_ID_PRESUPUESTO, P_ANIO, P_MES) AS PORCENTAJE
        FROM   CATEGORIA           C
        INNER JOIN   SUBCATEGORIA        S ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        LEFT JOIN PRESUPUESTO_DETALLE D ON D.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
                                       AND D.ID_PRESUPUESTO  = P_ID_PRESUPUESTO
        WHERE  S.ACTIVA = 1
        ORDER  BY C.TIPO, C.ORDEN, C.NOMBRE, S.NOMBRE;
END SP_RESUMEN_PRESUPUESTO_MES;
/
