-- ============================================================
-- SISTEMA DE PRESUPUESTO PERSONAL
-- Steve Valladares - 22341344
-- ============================================================



-- PROCEDURES: USUARIO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO (
    P_ID_USER          IN USUARIO.ID_USER%TYPE,
    P_PRIMER_NOMBRE    IN USUARIO.PRIMER_NOMBRE%TYPE,
    P_SEGUNDO_NOMBRE   IN USUARIO.SEGUNDO_NOMBRE%TYPE,
    P_PRIMER_APELLIDO  IN USUARIO.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO IN USUARIO.SEGUNDO_APELLIDO%TYPE,
    P_CORREO           IN USUARIO.CORREO%TYPE,
    P_PASSWORD         IN USUARIO.PASSWORD%TYPE,
    P_SALARIO_BASE     IN USUARIO.SALARIO_BASE%TYPE
) AS
BEGIN
    INSERT INTO USUARIO (
        ID_USER, PRIMER_NOMBRE, SEGUNDO_NOMBRE,
        PRIMER_APELLIDO, SEGUNDO_APELLIDO,
        CORREO, PASSWORD, FECHA_REGISTRO,
        SALARIO_BASE, ESTADO
    ) VALUES (
        P_ID_USER, P_PRIMER_NOMBRE, P_SEGUNDO_NOMBRE,
        P_PRIMER_APELLIDO, P_SEGUNDO_APELLIDO,
        P_CORREO, P_PASSWORD, SYSDATE,
        P_SALARIO_BASE, 1
    );
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe un usuario con ese ID o correo.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_USUARIO;



-----------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO (
    P_ID_USER          IN USUARIO.ID_USER%TYPE,
    P_PRIMER_NOMBRE    IN USUARIO.PRIMER_NOMBRE%TYPE,
    P_SEGUNDO_NOMBRE   IN USUARIO.SEGUNDO_NOMBRE%TYPE,
    P_PRIMER_APELLIDO  IN USUARIO.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO IN USUARIO.SEGUNDO_APELLIDO%TYPE,
    P_SALARIO_BASE     IN USUARIO.SALARIO_BASE%TYPE
) AS
BEGIN
    UPDATE USUARIO SET
        PRIMER_NOMBRE    = P_PRIMER_NOMBRE,
        SEGUNDO_NOMBRE   = P_SEGUNDO_NOMBRE,
        PRIMER_APELLIDO  = P_PRIMER_APELLIDO,
        SEGUNDO_APELLIDO = P_SEGUNDO_APELLIDO,
        SALARIO_BASE     = P_SALARIO_BASE
    WHERE ID_USER = P_ID_USER;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el usuario: ' || P_ID_USER);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ACTUALIZAR_USUARIO;


-----------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_USUARIO (
    P_ID_USER IN USUARIO.ID_USER%TYPE
) AS
BEGIN
    UPDATE USUARIO SET ESTADO = 0
    WHERE ID_USER = P_ID_USER;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el usuario: ' || P_ID_USER);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ELIMINAR_USUARIO;


-----------------------
CREATE OR REPLACE PROCEDURE SP_LISTAR_USUARIOS (
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM USUARIO ORDER BY PRIMER_APELLIDO, PRIMER_NOMBRE;
END SP_LISTAR_USUARIOS;
/


--PROCEDURES: CATEGORIA Y SUBCATEGORIA
CREATE OR REPLACE PROCEDURE SP_INSERTAR_CATEGORIA (
    P_ID_CATEGORIA   IN CATEGORIA.ID_CATEGORIA%TYPE,
    P_NOMBRE         IN CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION    IN CATEGORIA.DESCRIPCION%TYPE,
    P_TIPO           IN CATEGORIA.TIPO%TYPE,
    P_NOMBRE_ICON_UI IN CATEGORIA.NOMBRE_ICON_UI%TYPE,
    P_COLOR_HEX      IN CATEGORIA.COLOR_HEX%TYPE,
    P_ORDEN          IN CATEGORIA.ORDEN%TYPE
) AS
BEGIN
    IF P_TIPO NOT IN ('ingreso','gasto','ahorro') THEN
        RAISE_APPLICATION_ERROR(-20010, 'Tipo inválido. Debe ser: ingreso, gasto o ahorro.');
    END IF;

    INSERT INTO CATEGORIA (
        ID_CATEGORIA, NOMBRE, DESCRIPCION,
        TIPO, NOMBRE_ICON_UI, COLOR_HEX, ORDEN
    ) VALUES (
        P_ID_CATEGORIA, P_NOMBRE, P_DESCRIPCION,
        P_TIPO, P_NOMBRE_ICON_UI, P_COLOR_HEX, P_ORDEN
    );
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe una categoría con ese ID.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_CATEGORIA;


-----------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CATEGORIA (
    P_ID_CATEGORIA IN CATEGORIA.ID_CATEGORIA%TYPE,
    P_NOMBRE       IN CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION  IN CATEGORIA.DESCRIPCION%TYPE,
    P_COLOR_HEX    IN CATEGORIA.COLOR_HEX%TYPE,
    P_ORDEN        IN CATEGORIA.ORDEN%TYPE
) AS
BEGIN
    UPDATE CATEGORIA SET
        NOMBRE      = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION,
        COLOR_HEX   = P_COLOR_HEX,
        ORDEN       = P_ORDEN
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la categoría: ' || P_ID_CATEGORIA);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ACTUALIZAR_CATEGORIA;


-----------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN SUBCATEGORIA.ID_SUBCATEGORIA%TYPE,
    P_ID_CATEGORIA    IN SUBCATEGORIA.ID_CATEGORIA%TYPE,
    P_NOMBRE          IN SUBCATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION     IN SUBCATEGORIA.DESCRIPCION%TYPE
) AS
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE
    FROM CATEGORIA WHERE ID_CATEGORIA = P_ID_CATEGORIA;

    IF V_EXISTE = 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'No existe la categoría: ' || P_ID_CATEGORIA);
    END IF;

    INSERT INTO SUBCATEGORIA (
        ID_SUBCATEGORIA, ID_CATEGORIA,
        NOMBRE, DESCRIPCION, ACTIVA, SUB_POR_DEFECTO
    ) VALUES (
        P_ID_SUBCATEGORIA, P_ID_CATEGORIA,
        P_NOMBRE, P_DESCRIPCION, 1, 0
    );
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe una subcategoría con ese ID.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_SUBCATEGORIA;


-----------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN SUBCATEGORIA.ID_SUBCATEGORIA%TYPE
) AS
    V_ID_CATEGORIA SUBCATEGORIA.ID_CATEGORIA%TYPE;
    V_ACTIVAS      NUMBER;
BEGIN
    SELECT ID_CATEGORIA INTO V_ID_CATEGORIA
    FROM SUBCATEGORIA WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    SELECT COUNT(*) INTO V_ACTIVAS
    FROM SUBCATEGORIA
    WHERE ID_CATEGORIA = V_ID_CATEGORIA AND ACTIVA = 1;

    IF V_ACTIVAS <= 1 THEN
        RAISE_APPLICATION_ERROR(-20012,
            'No se puede desactivar: es la única subcategoría activa de la categoría.');
    END IF;

    UPDATE SUBCATEGORIA SET ACTIVA = 0
    WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la subcategoría: ' || P_ID_SUBCATEGORIA);
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ELIMINAR_SUBCATEGORIA;




-- PROCEDURES: PRESUPUESTO Y PRESUPUESTO_DETALLE


CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRESUPUESTO (
    P_ID_PRESUPUESTO     IN PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_ID_USER            IN PRESUPUESTO.ID_USER%TYPE,
    P_NOMBRE_DESCRIPTIVO IN PRESUPUESTO.NOMBRE_DESCRIPTIVO%TYPE,
    P_ANIO_INICIO        IN PRESUPUESTO.ANIO_INICIO%TYPE,
    P_MES_INICIO         IN PRESUPUESTO.MES_INICIO%TYPE,
    P_ANIO_FIN           IN PRESUPUESTO.ANIO_FIN%TYPE,
    P_MES_FIN            IN PRESUPUESTO.MES_FIN%TYPE
) AS
BEGIN
    IF P_ANIO_FIN < P_ANIO_INICIO OR
      (P_ANIO_FIN = P_ANIO_INICIO AND P_MES_FIN < P_MES_INICIO) THEN
        RAISE_APPLICATION_ERROR(-20020,
            'El período de fin no puede ser anterior al período de inicio.');
    END IF;

    INSERT INTO PRESUPUESTO (
        ID_PRESUPUESTO, ID_USER, NOMBRE_DESCRIPTIVO,
        ANIO_INICIO, MES_INICIO, ANIO_FIN, MES_FIN,
        TOTAL_INGRESOS, TOTAL_GASTOS, TOTAL_AHORRO,
        FECHA_HORA_CREACION, ESTADO_PRESUPUESTO
    ) VALUES (
        P_ID_PRESUPUESTO, P_ID_USER, P_NOMBRE_DESCRIPTIVO,
        P_ANIO_INICIO, P_MES_INICIO, P_ANIO_FIN, P_MES_FIN,
        0, 0, 0, SYSTIMESTAMP, 'activo'
    );
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe un presupuesto con ese ID.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_PRESUPUESTO;
/


-----------------------
CREATE OR REPLACE PROCEDURE SP_CERRAR_PRESUPUESTO (
    P_ID_PRESUPUESTO IN PRESUPUESTO.ID_PRESUPUESTO%TYPE
) AS
BEGIN
    UPDATE PRESUPUESTO SET ESTADO_PRESUPUESTO = 'cerrado'
    WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el presupuesto: ' || P_ID_PRESUPUESTO);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_CERRAR_PRESUPUESTO;
/


-----------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRESUPUESTO_DETALLE (
    P_ID_DETALLE      IN PRESUPUESTO_DETALLE.ID_DETALLE%TYPE,
    P_ID_PRESUPUESTO  IN PRESUPUESTO_DETALLE.ID_PRESUPUESTO%TYPE,
    P_ID_SUBCATEGORIA IN PRESUPUESTO_DETALLE.ID_SUBCATEGORIA%TYPE,
    P_MONTO           IN PRESUPUESTO_DETALLE.MONTO%TYPE,
    P_JUSTIFICACION   IN PRESUPUESTO_DETALLE.JUSTIFICACION%TYPE
) AS
    V_ESTADO VARCHAR2(10);
BEGIN
    SELECT ESTADO_PRESUPUESTO INTO V_ESTADO
    FROM PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    IF V_ESTADO != 'activo' THEN
        RAISE_APPLICATION_ERROR(-20022,
            'Solo se pueden agregar detalles a presupuestos activos.');
    END IF;

    INSERT INTO PRESUPUESTO_DETALLE (
        ID_DETALLE, ID_PRESUPUESTO,
        ID_SUBCATEGORIA, MONTO, JUSTIFICACION
    ) VALUES (
        P_ID_DETALLE, P_ID_PRESUPUESTO,
        P_ID_SUBCATEGORIA, P_MONTO, P_JUSTIFICACION
    );
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el presupuesto: ' || P_ID_PRESUPUESTO);
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe un detalle con ese ID o subcategoría.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_PRESUPUESTO_DETALLE;
/


-----------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRESUPUESTO_DETALLE (
    P_ID_DETALLE    IN PRESUPUESTO_DETALLE.ID_DETALLE%TYPE,
    P_MONTO         IN PRESUPUESTO_DETALLE.MONTO%TYPE,
    P_JUSTIFICACION IN PRESUPUESTO_DETALLE.JUSTIFICACION%TYPE
) AS
BEGIN
    UPDATE PRESUPUESTO_DETALLE SET
        MONTO         = P_MONTO,
        JUSTIFICACION = P_JUSTIFICACION
    WHERE ID_DETALLE = P_ID_DETALLE;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el detalle: ' || P_ID_DETALLE);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ACTUALIZAR_PRESUPUESTO_DETALLE;
/


-- STORED PROCEDURES: TRANSACCION Y OBLIGACION_FIJA

CREATE OR REPLACE PROCEDURE SP_INSERTAR_TRANSACCION (
    P_ID_TRANSACCION  IN TRANSACCION.ID_TRANSACCION%TYPE,
    P_ID_USER         IN TRANSACCION.ID_USER%TYPE,
    P_ID_PRESUPUESTO  IN TRANSACCION.ID_PRESUPUESTO%TYPE,
    P_ID_SUBCATEGORIA IN TRANSACCION.ID_SUBCATEGORIA%TYPE,
    P_ANIO            IN TRANSACCION.ANIO%TYPE,
    P_MES             IN TRANSACCION.MES%TYPE,
    P_TIPO            IN TRANSACCION.TIPO%TYPE,
    P_DESCRIPCION     IN TRANSACCION.DESCRIPCION%TYPE,
    P_MONTO           IN TRANSACCION.MONTO%TYPE,
    P_FECHA           IN TRANSACCION.FECHA_TRANSACCION%TYPE,
    P_METODO_PAGO     IN TRANSACCION.METODO_PAGO%TYPE,
    P_NUM_FACTURA     IN TRANSACCION.NUM_FACTURA%TYPE,
    P_OBSERVACIONES   IN TRANSACCION.OBSERVACIONES%TYPE
) AS
    V_TIPO_SUBCAT VARCHAR2(10);
BEGIN
    -- Validar tipo vs subcategoría
    SELECT C.TIPO INTO V_TIPO_SUBCAT
    FROM   SUBCATEGORIA S
    JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF V_TIPO_SUBCAT != P_TIPO THEN
        RAISE_APPLICATION_ERROR(-20031,
            'El tipo de transacción no coincide con el tipo de la subcategoría.');
    END IF;

    INSERT INTO TRANSACCION (
        ID_TRANSACCION, ID_USER, ID_PRESUPUESTO,
        ID_SUBCATEGORIA, ANIO, MES, TIPO,
        DESCRIPCION, MONTO, FECHA_TRANSACCION,
        METODO_PAGO, NUM_FACTURA, OBSERVACIONES,
        FECHA_HORA_REGISTRO
    ) VALUES (
        P_ID_TRANSACCION, P_ID_USER, P_ID_PRESUPUESTO,
        P_ID_SUBCATEGORIA, P_ANIO, P_MES, P_TIPO,
        P_DESCRIPCION, P_MONTO, P_FECHA,
        P_METODO_PAGO, P_NUM_FACTURA, P_OBSERVACIONES,
        SYSTIMESTAMP
    );
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el presupuesto o subcategoría.');
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe una transacción con ese ID.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_TRANSACCION;
/


-----------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_TRANSACCION (
    P_ID_TRANSACCION IN TRANSACCION.ID_TRANSACCION%TYPE
) AS
BEGIN
    DELETE FROM OBLIGACION_TRANSACCION WHERE ID_TRANSACCION = P_ID_TRANSACCION;
    DELETE FROM TRANSACCION            WHERE ID_TRANSACCION = P_ID_TRANSACCION;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la transacción: ' || P_ID_TRANSACCION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ELIMINAR_TRANSACCION;
/


-----------------------
CREATE OR REPLACE PROCEDURE SP_INSERTAR_OBLIGACION (
    P_ID_OBLIGACION   IN OBLIGACION_FIJA.ID_OBLIGACION%TYPE,
    P_ID_USER         IN OBLIGACION_FIJA.ID_USER%TYPE,
    P_ID_SUBCATEGORIA IN OBLIGACION_FIJA.ID_SUBCATEGORIA%TYPE,
    P_NOMBRE          IN OBLIGACION_FIJA.NOMBRE%TYPE,
    P_DESCRIPCION     IN OBLIGACION_FIJA.DESCRIPCION%TYPE,
    P_MONTO           IN OBLIGACION_FIJA.MONTO%TYPE,
    P_DIA             IN OBLIGACION_FIJA.DIA%TYPE,
    P_FECHA_INICIO    IN OBLIGACION_FIJA.FECHA_INICIO%TYPE,
    P_FECHA_FIN       IN OBLIGACION_FIJA.FECHA_FIN%TYPE
) AS
    V_TIPO VARCHAR2(10);
BEGIN
    SELECT C.TIPO INTO V_TIPO
    FROM   SUBCATEGORIA S
    JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF V_TIPO != 'gasto' THEN
        RAISE_APPLICATION_ERROR(-20040,
            'Las obligaciones fijas solo aplican a subcategorías de tipo gasto.');
    END IF;

    INSERT INTO OBLIGACION_FIJA (
        ID_OBLIGACION, ID_USER, ID_SUBCATEGORIA,
        NOMBRE, DESCRIPCION, MONTO,
        DIA, VIGENTE, FECHA_INICIO, FECHA_FIN
    ) VALUES (
        P_ID_OBLIGACION, P_ID_USER, P_ID_SUBCATEGORIA,
        P_NOMBRE, P_DESCRIPCION, P_MONTO,
        P_DIA, 1, P_FECHA_INICIO, P_FECHA_FIN
    );
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la subcategoría: ' || P_ID_SUBCATEGORIA);
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe una obligación con ese ID.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_OBLIGACION;
/


-----------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_OBLIGACION (
    P_ID_OBLIGACION IN OBLIGACION_FIJA.ID_OBLIGACION%TYPE
) AS
BEGIN
    UPDATE OBLIGACION_FIJA SET VIGENTE = 0
    WHERE ID_OBLIGACION = P_ID_OBLIGACION;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la obligación: ' || P_ID_OBLIGACION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ELIMINAR_OBLIGACION;
/
