-- ============================================================
-- SISTEMA DE PRESUPUESTO PERSONAL
-- Autor: Steve Valladares - 22341344
-- ============================================================
-- sqlplus system/OracleTBD@localhost:1521/XE @"C:\Users\EzTiB\source\repos\TBD1_Proyecto\TBD1_Proyecto\SQL\stored_procedures.sql"
-- ============================================================

-- ============================================================
-- CRUD: USUARIO
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO (
    P_PRIMER_NOMBRE    IN  USUARIO.PRIMER_NOMBRE%TYPE,
    P_SEGUNDO_NOMBRE   IN  USUARIO.SEGUNDO_NOMBRE%TYPE,
    P_PRIMER_APELLIDO  IN  USUARIO.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO IN  USUARIO.SEGUNDO_APELLIDO%TYPE,
    P_CORREO           IN  USUARIO.CORREO%TYPE,
    P_PASSWORD         IN  USUARIO.PASSWORD%TYPE,
    P_SALARIO_BASE     IN  USUARIO.SALARIO_BASE%TYPE,
    P_ID_GENERADO      OUT USUARIO.ID_USER%TYPE --Sequence
) AS
BEGIN
    IF TRIM(P_PRIMER_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'El primer nombre es obligatorio.');
    END IF;
    IF TRIM(P_PRIMER_APELLIDO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20101, 'El primer apellido es obligatorio.');
    END IF;
    IF TRIM(P_CORREO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20102, 'El correo es obligatorio.');
    END IF;
    IF TRIM(P_PASSWORD) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20103, 'La contraseña es obligatoria.');
    END IF;
    IF P_SALARIO_BASE < 0 THEN
        RAISE_APPLICATION_ERROR(-20104, 'El salario no puede ser negativo.');
    END IF;

    INSERT INTO USUARIO (
        ID_USER, PRIMER_NOMBRE, SEGUNDO_NOMBRE,
        PRIMER_APELLIDO, SEGUNDO_APELLIDO,
        CORREO, PASSWORD, FECHA_REGISTRO,
        SALARIO_BASE, ESTADO
    ) VALUES (
        NULL,
        P_PRIMER_NOMBRE, P_SEGUNDO_NOMBRE,
        P_PRIMER_APELLIDO, P_SEGUNDO_APELLIDO,
        P_CORREO, P_PASSWORD, SYSDATE,
        P_SALARIO_BASE, 1
    ) RETURNING ID_USER INTO P_ID_GENERADO;

    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe un usuario con ese correo.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_USUARIO;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO (
    P_ID_USER          IN USUARIO.ID_USER%TYPE,
    P_PRIMER_NOMBRE    IN USUARIO.PRIMER_NOMBRE%TYPE,
    P_SEGUNDO_NOMBRE   IN USUARIO.SEGUNDO_NOMBRE%TYPE,
    P_PRIMER_APELLIDO  IN USUARIO.PRIMER_APELLIDO%TYPE,
    P_SEGUNDO_APELLIDO IN USUARIO.SEGUNDO_APELLIDO%TYPE,
    P_SALARIO_BASE     IN USUARIO.SALARIO_BASE%TYPE
) AS
BEGIN
    IF TRIM(P_PRIMER_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'El primer nombre es obligatorio.');
    END IF;
    IF P_SALARIO_BASE < 0 THEN
        RAISE_APPLICATION_ERROR(-20104, 'El salario no puede ser negativo.');
    END IF;

    UPDATE USUARIO SET
        PRIMER_NOMBRE    = P_PRIMER_NOMBRE,
        SEGUNDO_NOMBRE   = P_SEGUNDO_NOMBRE,
        PRIMER_APELLIDO  = P_PRIMER_APELLIDO,
        SEGUNDO_APELLIDO = P_SEGUNDO_APELLIDO,
        SALARIO_BASE     = P_SALARIO_BASE
    WHERE ID_USER = P_ID_USER;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el usuario: ' || P_ID_USER);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_USUARIO;
/

-- Soft delete: desactiva el usuario en lugar de eliminarlo
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_USUARIO (
    P_ID_USER IN USUARIO.ID_USER%TYPE
) AS
BEGIN
    UPDATE USUARIO SET ESTADO = 0 WHERE ID_USER = P_ID_USER;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el usuario: ' || P_ID_USER);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_USUARIO;
/

CREATE OR REPLACE PROCEDURE SP_CONSULTAR_USUARIO (
    P_ID_USER IN  USUARIO.ID_USER%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM USUARIO WHERE ID_USER = P_ID_USER;
END SP_CONSULTAR_USUARIO;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_USUARIOS (
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM USUARIO
        WHERE ESTADO = 1
        ORDER BY PRIMER_APELLIDO, PRIMER_NOMBRE;
END SP_LISTAR_USUARIOS;
/

-- ============================================================
-- CRUD: CATEGORIA
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_CATEGORIA (
    P_NOMBRE         IN  CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION    IN  CATEGORIA.DESCRIPCION%TYPE,
    P_TIPO           IN  CATEGORIA.TIPO%TYPE,
    P_NOMBRE_ICON_UI IN  CATEGORIA.NOMBRE_ICON_UI%TYPE,
    P_COLOR_HEX      IN  CATEGORIA.COLOR_HEX%TYPE,
    P_ORDEN          IN  CATEGORIA.ORDEN%TYPE,
    P_ID_GENERADO    OUT CATEGORIA.ID_CATEGORIA%TYPE
) AS
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20110, 'El nombre de la categoría es obligatorio.');
    END IF;
    IF P_TIPO NOT IN ('ingreso','gasto','ahorro') THEN
        RAISE_APPLICATION_ERROR(-20111, 'Tipo inválido. Valores: ingreso, gasto, ahorro.');
    END IF;
    IF P_ORDEN < 0 THEN
        RAISE_APPLICATION_ERROR(-20112, 'El orden no puede ser negativo.');
    END IF;

    INSERT INTO CATEGORIA (
        ID_CATEGORIA, NOMBRE, DESCRIPCION,
        TIPO, NOMBRE_ICON_UI, COLOR_HEX, ORDEN
    ) VALUES (
        NULL, P_NOMBRE, P_DESCRIPCION,
        P_TIPO, P_NOMBRE_ICON_UI, P_COLOR_HEX, P_ORDEN
    ) RETURNING ID_CATEGORIA INTO P_ID_GENERADO;
    -- TRG_SUBCAT_DEFECTO crea la subcategoría "General" automáticamente aquí
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe una categoría con ese ID.');
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_CATEGORIA;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CATEGORIA (
    P_ID_CATEGORIA IN CATEGORIA.ID_CATEGORIA%TYPE,
    P_NOMBRE       IN CATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION  IN CATEGORIA.DESCRIPCION%TYPE,
    P_COLOR_HEX    IN CATEGORIA.COLOR_HEX%TYPE,
    P_ORDEN        IN CATEGORIA.ORDEN%TYPE
) AS
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20110, 'El nombre de la categoría es obligatorio.');
    END IF;
    IF P_ORDEN < 0 THEN
        RAISE_APPLICATION_ERROR(-20112, 'El orden no puede ser negativo.');
    END IF;

    UPDATE CATEGORIA SET
        NOMBRE      = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION,
        COLOR_HEX   = P_COLOR_HEX,
        ORDEN       = P_ORDEN
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la categoría: ' || P_ID_CATEGORIA);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_CATEGORIA;
/

-- No se elimina una categoría si tiene transacciones asociadas
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_CATEGORIA (
    P_ID_CATEGORIA IN CATEGORIA.ID_CATEGORIA%TYPE
) AS
    V_TIENE_TRX NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TIENE_TRX
    FROM   TRANSACCION T
    JOIN   SUBCATEGORIA S ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
    WHERE  S.ID_CATEGORIA = P_ID_CATEGORIA;

    IF V_TIENE_TRX > 0 THEN
        RAISE_APPLICATION_ERROR(-20113,
            'No se puede eliminar: la categoría tiene ' || V_TIENE_TRX || ' transacción(es) asociada(s).');
    END IF;

    DELETE FROM SUBCATEGORIA  WHERE ID_CATEGORIA  = P_ID_CATEGORIA;
    DELETE FROM CATEGORIA     WHERE ID_CATEGORIA  = P_ID_CATEGORIA;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la categoría: ' || P_ID_CATEGORIA);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_CATEGORIA;
/

CREATE OR REPLACE PROCEDURE SP_CONSULTAR_CATEGORIA (
    P_ID_CATEGORIA IN  CATEGORIA.ID_CATEGORIA%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM CATEGORIA WHERE ID_CATEGORIA = P_ID_CATEGORIA;
END SP_CONSULTAR_CATEGORIA;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_CATEGORIAS (
    P_TIPO   IN  VARCHAR2,   -- NULL = todas
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    IF P_TIPO IS NULL THEN
        OPEN P_CURSOR FOR
            SELECT * FROM CATEGORIA ORDER BY ORDEN, NOMBRE;
    ELSE
        OPEN P_CURSOR FOR
            SELECT * FROM CATEGORIA
            WHERE TIPO = P_TIPO ORDER BY ORDEN, NOMBRE;
    END IF;
END SP_LISTAR_CATEGORIAS;
/

-- ============================================================
-- CRUD: SUBCATEGORIA
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_SUBCATEGORIA (
    P_ID_CATEGORIA    IN  SUBCATEGORIA.ID_CATEGORIA%TYPE,
    P_NOMBRE          IN  SUBCATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION     IN  SUBCATEGORIA.DESCRIPCION%TYPE,
    P_ID_GENERADO     OUT SUBCATEGORIA.ID_SUBCATEGORIA%TYPE
) AS
    V_EXISTE NUMBER;
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20120, 'El nombre de la subcategoría es obligatorio.');
    END IF;

    SELECT COUNT(*) INTO V_EXISTE FROM CATEGORIA WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    IF V_EXISTE = 0 THEN
        RAISE_APPLICATION_ERROR(-20121, 'No existe la categoría: ' || P_ID_CATEGORIA);
    END IF;

    INSERT INTO SUBCATEGORIA (
        ID_SUBCATEGORIA, ID_CATEGORIA,
        NOMBRE, DESCRIPCION, ACTIVA, SUB_POR_DEFECTO
    ) VALUES (
        NULL, P_ID_CATEGORIA,
        P_NOMBRE, P_DESCRIPCION, 1, 0
    ) RETURNING ID_SUBCATEGORIA INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_SUBCATEGORIA;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN SUBCATEGORIA.ID_SUBCATEGORIA%TYPE,
    P_NOMBRE          IN SUBCATEGORIA.NOMBRE%TYPE,
    P_DESCRIPCION     IN SUBCATEGORIA.DESCRIPCION%TYPE
) AS
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20120, 'El nombre de la subcategoría es obligatorio.');
    END IF;

    UPDATE SUBCATEGORIA SET
        NOMBRE      = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION
    WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la subcategoría: ' || P_ID_SUBCATEGORIA);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_SUBCATEGORIA;
/

-- No permite desactivar si es la única activa de su categoría
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN SUBCATEGORIA.ID_SUBCATEGORIA%TYPE
) AS
    V_ID_CATEGORIA SUBCATEGORIA.ID_CATEGORIA%TYPE;
    V_ACTIVAS      NUMBER;
    V_TIENE_TRX    NUMBER;
BEGIN
    SELECT ID_CATEGORIA INTO V_ID_CATEGORIA
    FROM   SUBCATEGORIA WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    SELECT COUNT(*) INTO V_TIENE_TRX
    FROM   TRANSACCION WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
    IF V_TIENE_TRX > 0 THEN
        RAISE_APPLICATION_ERROR(-20122,
            'No se puede desactivar: tiene ' || V_TIENE_TRX || ' transacción(es) asociada(s).');
    END IF;

    SELECT COUNT(*) INTO V_ACTIVAS
    FROM   SUBCATEGORIA WHERE ID_CATEGORIA = V_ID_CATEGORIA AND ACTIVA = 1;
    IF V_ACTIVAS <= 1 THEN
        RAISE_APPLICATION_ERROR(-20123,
            'No se puede desactivar: es la única subcategoría activa de la categoría.');
    END IF;

    UPDATE SUBCATEGORIA SET ACTIVA = 0 WHERE ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la subcategoría: ' || P_ID_SUBCATEGORIA);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_SUBCATEGORIA;
/

CREATE OR REPLACE PROCEDURE SP_CONSULTAR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA IN  SUBCATEGORIA.ID_SUBCATEGORIA%TYPE,
    P_CURSOR          OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT S.*, C.NOMBRE AS NOMBRE_CATEGORIA, C.TIPO
        FROM   SUBCATEGORIA S
        JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
        WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;
END SP_CONSULTAR_SUBCATEGORIA;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_SUBCATEGORIAS (
    P_ID_CATEGORIA IN  SUBCATEGORIA.ID_CATEGORIA%TYPE,
    P_CURSOR       OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT S.*, C.NOMBRE AS NOMBRE_CATEGORIA, C.TIPO
        FROM   SUBCATEGORIA S
        JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
        WHERE  S.ID_CATEGORIA = P_ID_CATEGORIA
        AND    S.ACTIVA = 1
        ORDER  BY S.SUB_POR_DEFECTO DESC, S.NOMBRE;
END SP_LISTAR_SUBCATEGORIAS;
/

-- ============================================================
-- CRUD: PRESUPUESTO
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRESUPUESTO (
    P_ID_USER            IN  PRESUPUESTO.ID_USER%TYPE,
    P_NOMBRE_DESCRIPTIVO IN  PRESUPUESTO.NOMBRE_DESCRIPTIVO%TYPE,
    P_ANIO_INICIO        IN  PRESUPUESTO.ANIO_INICIO%TYPE,
    P_MES_INICIO         IN  PRESUPUESTO.MES_INICIO%TYPE,
    P_ANIO_FIN           IN  PRESUPUESTO.ANIO_FIN%TYPE,
    P_MES_FIN            IN  PRESUPUESTO.MES_FIN%TYPE,
    P_ID_GENERADO        OUT PRESUPUESTO.ID_PRESUPUESTO%TYPE
) AS
BEGIN
    IF TRIM(P_NOMBRE_DESCRIPTIVO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20130, 'El nombre descriptivo es obligatorio.');
    END IF;
    IF P_ANIO_INICIO < 2000 OR P_ANIO_FIN < 2000 THEN
        RAISE_APPLICATION_ERROR(-20131, 'El año debe ser mayor a 2000.');
    END IF;
    IF P_ANIO_FIN < P_ANIO_INICIO OR
      (P_ANIO_FIN = P_ANIO_INICIO AND P_MES_FIN < P_MES_INICIO) THEN
        RAISE_APPLICATION_ERROR(-20132, 'El período fin no puede ser anterior al inicio.');
    END IF;

    INSERT INTO PRESUPUESTO (
        ID_PRESUPUESTO, ID_USER, NOMBRE_DESCRIPTIVO,
        ANIO_INICIO, MES_INICIO, ANIO_FIN, MES_FIN,
        TOTAL_INGRESOS, TOTAL_GASTOS, TOTAL_AHORRO,
        FECHA_HORA_CREACION, ESTADO_PRESUPUESTO
    ) VALUES (
        NULL, P_ID_USER, P_NOMBRE_DESCRIPTIVO,
        P_ANIO_INICIO, P_MES_INICIO, P_ANIO_FIN, P_MES_FIN,
        0, 0, 0, SYSTIMESTAMP, 'activo'
    ) RETURNING ID_PRESUPUESTO INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_PRESUPUESTO;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRESUPUESTO (
    P_ID_PRESUPUESTO     IN PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_NOMBRE_DESCRIPTIVO IN PRESUPUESTO.NOMBRE_DESCRIPTIVO%TYPE
) AS
    V_ESTADO VARCHAR2(10);
BEGIN
    SELECT ESTADO_PRESUPUESTO INTO V_ESTADO
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    IF V_ESTADO = 'cerrado' THEN
        RAISE_APPLICATION_ERROR(-20133, 'No se puede modificar un presupuesto cerrado.');
    END IF;
    IF TRIM(P_NOMBRE_DESCRIPTIVO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20130, 'El nombre descriptivo es obligatorio.');
    END IF;

    UPDATE PRESUPUESTO SET NOMBRE_DESCRIPTIVO = P_NOMBRE_DESCRIPTIVO
    WHERE  ID_PRESUPUESTO = P_ID_PRESUPUESTO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el presupuesto: ' || P_ID_PRESUPUESTO);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_PRESUPUESTO;
/

CREATE OR REPLACE PROCEDURE SP_CERRAR_PRESUPUESTO (
    P_ID_PRESUPUESTO IN PRESUPUESTO.ID_PRESUPUESTO%TYPE
) AS
    V_ESTADO VARCHAR2(10);
BEGIN
    SELECT ESTADO_PRESUPUESTO INTO V_ESTADO
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;

    IF V_ESTADO = 'cerrado' THEN
        RAISE_APPLICATION_ERROR(-20134, 'El presupuesto ya está cerrado.');
    END IF;

    UPDATE PRESUPUESTO SET ESTADO_PRESUPUESTO = 'cerrado'
    WHERE  ID_PRESUPUESTO = P_ID_PRESUPUESTO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el presupuesto: ' || P_ID_PRESUPUESTO);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_CERRAR_PRESUPUESTO;
/

CREATE OR REPLACE PROCEDURE SP_CONSULTAR_PRESUPUESTO (
    P_ID_PRESUPUESTO IN  PRESUPUESTO.ID_PRESUPUESTO%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;
END SP_CONSULTAR_PRESUPUESTO;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_PRESUPUESTOS (
    P_ID_USER IN  PRESUPUESTO.ID_USER%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT * FROM PRESUPUESTO
        WHERE  ID_USER = P_ID_USER
        ORDER  BY ANIO_INICIO DESC, MES_INICIO DESC;
END SP_LISTAR_PRESUPUESTOS;
/

-- ============================================================
-- CRUD: PRESUPUESTO_DETALLE
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_DETALLE (
    P_ID_PRESUPUESTO  IN  PRESUPUESTO_DETALLE.ID_PRESUPUESTO%TYPE,
    P_ID_SUBCATEGORIA IN  PRESUPUESTO_DETALLE.ID_SUBCATEGORIA%TYPE,
    P_MONTO           IN  PRESUPUESTO_DETALLE.MONTO%TYPE,
    P_JUSTIFICACION   IN  PRESUPUESTO_DETALLE.JUSTIFICACION%TYPE,
    P_ID_GENERADO     OUT PRESUPUESTO_DETALLE.ID_DETALLE%TYPE
) AS
    V_ESTADO VARCHAR2(10);
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20140, 'El monto del detalle debe ser mayor a cero.');
    END IF;

    SELECT ESTADO_PRESUPUESTO INTO V_ESTADO
    FROM   PRESUPUESTO WHERE ID_PRESUPUESTO = P_ID_PRESUPUESTO;
    IF V_ESTADO != 'activo' THEN
        RAISE_APPLICATION_ERROR(-20141, 'Solo se pueden agregar detalles a presupuestos activos.');
    END IF;

    INSERT INTO PRESUPUESTO_DETALLE (
        ID_DETALLE, ID_PRESUPUESTO, ID_SUBCATEGORIA, MONTO, JUSTIFICACION
    ) VALUES (
        NULL, P_ID_PRESUPUESTO, P_ID_SUBCATEGORIA, P_MONTO, P_JUSTIFICACION
    ) RETURNING ID_DETALLE INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el presupuesto: ' || P_ID_PRESUPUESTO);
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Esa subcategoría ya tiene un monto asignado en este presupuesto.');
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_DETALLE;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_DETALLE (
    P_ID_DETALLE    IN PRESUPUESTO_DETALLE.ID_DETALLE%TYPE,
    P_MONTO         IN PRESUPUESTO_DETALLE.MONTO%TYPE,
    P_JUSTIFICACION IN PRESUPUESTO_DETALLE.JUSTIFICACION%TYPE
) AS
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20140, 'El monto del detalle debe ser mayor a cero.');
    END IF;

    UPDATE PRESUPUESTO_DETALLE SET
        MONTO = P_MONTO, JUSTIFICACION = P_JUSTIFICACION
    WHERE ID_DETALLE = P_ID_DETALLE;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el detalle: ' || P_ID_DETALLE);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_DETALLE;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_DETALLE (
    P_ID_DETALLE IN PRESUPUESTO_DETALLE.ID_DETALLE%TYPE
) AS
BEGIN
    DELETE FROM PRESUPUESTO_DETALLE WHERE ID_DETALLE = P_ID_DETALLE;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró el detalle: ' || P_ID_DETALLE);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_DETALLE;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_DETALLES (
    P_ID_PRESUPUESTO IN  PRESUPUESTO_DETALLE.ID_PRESUPUESTO%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  D.ID_DETALLE, D.ID_PRESUPUESTO, D.ID_SUBCATEGORIA,
                D.MONTO, D.JUSTIFICACION,
                S.NOMBRE  AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE  AS NOMBRE_CATEGORIA,
                C.TIPO
        FROM    PRESUPUESTO_DETALLE D
        JOIN    SUBCATEGORIA        S ON D.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA           C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   D.ID_PRESUPUESTO = P_ID_PRESUPUESTO
        ORDER   BY C.TIPO, C.NOMBRE, S.NOMBRE;
END SP_LISTAR_DETALLES;
/

-- ============================================================
-- CRUD: TRANSACCION
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_TRANSACCION (
    P_ID_USER         IN  TRANSACCION.ID_USER%TYPE,
    P_ID_PRESUPUESTO  IN  TRANSACCION.ID_PRESUPUESTO%TYPE,
    P_ID_SUBCATEGORIA IN  TRANSACCION.ID_SUBCATEGORIA%TYPE,
    P_ANIO            IN  TRANSACCION.ANIO%TYPE,
    P_MES             IN  TRANSACCION.MES%TYPE,
    P_TIPO            IN  TRANSACCION.TIPO%TYPE,
    P_DESCRIPCION     IN  TRANSACCION.DESCRIPCION%TYPE,
    P_MONTO           IN  TRANSACCION.MONTO%TYPE,
    P_FECHA           IN  TRANSACCION.FECHA_TRANSACCION%TYPE,
    P_METODO_PAGO     IN  TRANSACCION.METODO_PAGO%TYPE,
    P_NUM_FACTURA     IN  TRANSACCION.NUM_FACTURA%TYPE,
    P_OBSERVACIONES   IN  TRANSACCION.OBSERVACIONES%TYPE,
    P_ID_GENERADO     OUT TRANSACCION.ID_TRANSACCION%TYPE
) AS
    V_TIPO_SUBCAT VARCHAR2(10);
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20150, 'El monto de la transacción debe ser mayor a cero.');
    END IF;
    IF TRIM(P_DESCRIPCION) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20151, 'La descripción es obligatoria.');
    END IF;
    IF P_FECHA > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20152, 'La fecha de transacción no puede ser futura.');
    END IF;

    -- Validar tipo vs subcategoría
    SELECT C.TIPO INTO V_TIPO_SUBCAT
    FROM   SUBCATEGORIA S
    JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF V_TIPO_SUBCAT != P_TIPO THEN
        RAISE_APPLICATION_ERROR(-20153,
            'El tipo "' || P_TIPO || '" no coincide con el tipo de la subcategoría "' || V_TIPO_SUBCAT || '".');
    END IF;

    INSERT INTO TRANSACCION (
        ID_TRANSACCION, ID_USER, ID_PRESUPUESTO,
        ID_SUBCATEGORIA, ANIO, MES, TIPO,
        DESCRIPCION, MONTO, FECHA_TRANSACCION,
        METODO_PAGO, NUM_FACTURA, OBSERVACIONES,
        FECHA_HORA_REGISTRO
    ) VALUES (
        NULL, P_ID_USER, P_ID_PRESUPUESTO,
        P_ID_SUBCATEGORIA, P_ANIO, P_MES, P_TIPO,
        P_DESCRIPCION, P_MONTO, P_FECHA,
        P_METODO_PAGO, P_NUM_FACTURA, P_OBSERVACIONES,
        SYSTIMESTAMP
    ) RETURNING ID_TRANSACCION INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la subcategoría indicada.');
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_TRANSACCION;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_TRANSACCION (
    P_ID_TRANSACCION IN TRANSACCION.ID_TRANSACCION%TYPE,
    P_DESCRIPCION    IN TRANSACCION.DESCRIPCION%TYPE,
    P_MONTO          IN TRANSACCION.MONTO%TYPE,
    P_METODO_PAGO    IN TRANSACCION.METODO_PAGO%TYPE,
    P_NUM_FACTURA    IN TRANSACCION.NUM_FACTURA%TYPE,
    P_OBSERVACIONES  IN TRANSACCION.OBSERVACIONES%TYPE
) AS
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20150, 'El monto debe ser mayor a cero.');
    END IF;

    UPDATE TRANSACCION SET
        DESCRIPCION   = P_DESCRIPCION,
        MONTO         = P_MONTO,
        METODO_PAGO   = P_METODO_PAGO,
        NUM_FACTURA   = P_NUM_FACTURA,
        OBSERVACIONES = P_OBSERVACIONES
    WHERE ID_TRANSACCION = P_ID_TRANSACCION;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la transacción: ' || P_ID_TRANSACCION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_TRANSACCION;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_TRANSACCION (
    P_ID_TRANSACCION IN TRANSACCION.ID_TRANSACCION%TYPE
) AS
BEGIN
    DELETE FROM OBLIGACION_TRANSACCION WHERE ID_TRANSACCION = P_ID_TRANSACCION;
    DELETE FROM TRANSACCION            WHERE ID_TRANSACCION = P_ID_TRANSACCION;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la transacción: ' || P_ID_TRANSACCION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_TRANSACCION;
/

CREATE OR REPLACE PROCEDURE SP_CONSULTAR_TRANSACCION (
    P_ID_TRANSACCION IN  TRANSACCION.ID_TRANSACCION%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  T.*,
                S.NOMBRE AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE AS NOMBRE_CATEGORIA
        FROM    TRANSACCION  T
        JOIN    SUBCATEGORIA S ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA    C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   T.ID_TRANSACCION = P_ID_TRANSACCION;
END SP_CONSULTAR_TRANSACCION;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_TRANSACCIONES (
    P_ID_PRESUPUESTO IN  TRANSACCION.ID_PRESUPUESTO%TYPE,
    P_ANIO           IN  TRANSACCION.ANIO%TYPE,
    P_MES            IN  TRANSACCION.MES%TYPE,
    P_CURSOR         OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  T.ID_TRANSACCION, T.FECHA_TRANSACCION,
                T.ANIO, T.MES, T.TIPO,
                C.NOMBRE  AS NOMBRE_CATEGORIA,
                S.NOMBRE  AS NOMBRE_SUBCATEGORIA,
                T.DESCRIPCION, T.MONTO, T.METODO_PAGO
        FROM    TRANSACCION  T
        JOIN    SUBCATEGORIA S ON T.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA    C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   T.ID_PRESUPUESTO = P_ID_PRESUPUESTO
        AND     T.ANIO           = P_ANIO
        AND     T.MES            = P_MES
        ORDER   BY T.FECHA_TRANSACCION DESC;
END SP_LISTAR_TRANSACCIONES;
/

-- ============================================================
-- CRUD: OBLIGACION_FIJA
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_OBLIGACION (
    P_ID_USER         IN  OBLIGACION_FIJA.ID_USER%TYPE,
    P_ID_SUBCATEGORIA IN  OBLIGACION_FIJA.ID_SUBCATEGORIA%TYPE,
    P_NOMBRE          IN  OBLIGACION_FIJA.NOMBRE%TYPE,
    P_DESCRIPCION     IN  OBLIGACION_FIJA.DESCRIPCION%TYPE,
    P_MONTO           IN  OBLIGACION_FIJA.MONTO%TYPE,
    P_DIA             IN  OBLIGACION_FIJA.DIA%TYPE,
    P_FECHA_INICIO    IN  OBLIGACION_FIJA.FECHA_INICIO%TYPE,
    P_FECHA_FIN       IN  OBLIGACION_FIJA.FECHA_FIN%TYPE,
    P_ID_GENERADO     OUT OBLIGACION_FIJA.ID_OBLIGACION%TYPE
) AS
    V_TIPO VARCHAR2(10);
BEGIN
    IF TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20160, 'El nombre de la obligación es obligatorio.');
    END IF;
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20161, 'El monto debe ser mayor a cero.');
    END IF;
    IF P_DIA NOT BETWEEN 1 AND 31 THEN
        RAISE_APPLICATION_ERROR(-20162, 'El día de vencimiento debe estar entre 1 y 31.');
    END IF;
    IF P_FECHA_FIN IS NOT NULL AND P_FECHA_FIN <= P_FECHA_INICIO THEN
        RAISE_APPLICATION_ERROR(-20163, 'La fecha fin debe ser mayor a la fecha inicio.');
    END IF;

    SELECT C.TIPO INTO V_TIPO
    FROM   SUBCATEGORIA S
    JOIN   CATEGORIA    C ON S.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE  S.ID_SUBCATEGORIA = P_ID_SUBCATEGORIA;

    IF V_TIPO != 'gasto' THEN
        RAISE_APPLICATION_ERROR(-20164, 'Las obligaciones fijas solo aplican a subcategorías de tipo gasto.');
    END IF;

    INSERT INTO OBLIGACION_FIJA (
        ID_OBLIGACION, ID_USER, ID_SUBCATEGORIA,
        NOMBRE, DESCRIPCION, MONTO,
        DIA, VIGENTE, FECHA_INICIO, FECHA_FIN
    ) VALUES (
        NULL, P_ID_USER, P_ID_SUBCATEGORIA,
        P_NOMBRE, P_DESCRIPCION, P_MONTO,
        P_DIA, 1, P_FECHA_INICIO, P_FECHA_FIN
    ) RETURNING ID_OBLIGACION INTO P_ID_GENERADO;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la subcategoría: ' || P_ID_SUBCATEGORIA);
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_INSERTAR_OBLIGACION;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_OBLIGACION (
    P_ID_OBLIGACION   IN OBLIGACION_FIJA.ID_OBLIGACION%TYPE,
    P_NOMBRE          IN OBLIGACION_FIJA.NOMBRE%TYPE,
    P_DESCRIPCION     IN OBLIGACION_FIJA.DESCRIPCION%TYPE,
    P_MONTO           IN OBLIGACION_FIJA.MONTO%TYPE,
    P_DIA             IN OBLIGACION_FIJA.DIA%TYPE
) AS
BEGIN
    IF P_MONTO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20161, 'El monto debe ser mayor a cero.');
    END IF;
    IF P_DIA NOT BETWEEN 1 AND 31 THEN
        RAISE_APPLICATION_ERROR(-20162, 'El día debe estar entre 1 y 31.');
    END IF;

    UPDATE OBLIGACION_FIJA SET
        NOMBRE      = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION,
        MONTO       = P_MONTO,
        DIA         = P_DIA
    WHERE ID_OBLIGACION = P_ID_OBLIGACION;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la obligación: ' || P_ID_OBLIGACION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ACTUALIZAR_OBLIGACION;
/

-- Soft delete: marca como no vigente
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_OBLIGACION (
    P_ID_OBLIGACION IN OBLIGACION_FIJA.ID_OBLIGACION%TYPE
) AS
BEGIN
    UPDATE OBLIGACION_FIJA SET VIGENTE = 0 WHERE ID_OBLIGACION = P_ID_OBLIGACION;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se encontró la obligación: ' || P_ID_OBLIGACION);
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_ELIMINAR_OBLIGACION;
/

CREATE OR REPLACE PROCEDURE SP_CONSULTAR_OBLIGACION (
    P_ID_OBLIGACION IN  OBLIGACION_FIJA.ID_OBLIGACION%TYPE,
    P_CURSOR        OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  O.*,
                S.NOMBRE AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE AS NOMBRE_CATEGORIA,
                FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION) AS DIAS_VENCIMIENTO
        FROM    OBLIGACION_FIJA O
        JOIN    SUBCATEGORIA    S ON O.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA       C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   O.ID_OBLIGACION = P_ID_OBLIGACION;
END SP_CONSULTAR_OBLIGACION;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_OBLIGACIONES (
    P_ID_USER IN  OBLIGACION_FIJA.ID_USER%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT  O.*,
                S.NOMBRE AS NOMBRE_SUBCATEGORIA,
                C.NOMBRE AS NOMBRE_CATEGORIA,
                FN_DIAS_HASTA_VENCIMIENTO(O.ID_OBLIGACION) AS DIAS_VENCIMIENTO
        FROM    OBLIGACION_FIJA O
        JOIN    SUBCATEGORIA    S ON O.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
        JOIN    CATEGORIA       C ON S.ID_CATEGORIA    = C.ID_CATEGORIA
        WHERE   O.ID_USER  = P_ID_USER
        AND     O.VIGENTE  = 1
        ORDER   BY O.DIA;
END SP_LISTAR_OBLIGACIONES;
/
