
-- sqlplus system/OracleTBD@localhost:1521/XE @"C:\Users\EzTiB\source\repos\TBD1_Proyecto\TBD1_Proyecto\SQL\DDL_tablas.sql"

-- SEQUENCES
CREATE SEQUENCE SEQ_USUARIO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRESUPUESTO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORIA     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUBCATEGORIA  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETALLE       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_OBLIGACION    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSACCION   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



-- TABLAS
CREATE TABLE USUARIO (
    ID_USER           VARCHAR2(10)   PRIMARY KEY,
    PRIMER_NOMBRE     VARCHAR2(30)   NOT NULL,
    SEGUNDO_NOMBRE    VARCHAR2(30),
    PRIMER_APELLIDO   VARCHAR2(30)   NOT NULL,
    SEGUNDO_APELLIDO  VARCHAR2(30),
    CORREO            VARCHAR2(100)  NOT NULL UNIQUE,
    PASSWORD          VARCHAR2(50)   NOT NULL,
    FECHA_REGISTRO    DATE           DEFAULT SYSDATE,
    SALARIO_BASE      DECIMAL(10,2)  DEFAULT 0,
    ESTADO            NUMBER(1)      DEFAULT 1 CHECK (ESTADO IN (0,1)),
    CONSTRAINT CHK_SALARIO_POSITIVO CHECK (SALARIO_BASE >= 0)
);

CREATE TABLE PRESUPUESTO (
    ID_PRESUPUESTO       VARCHAR2(10)   PRIMARY KEY,
    ID_USER              VARCHAR2(10)   NOT NULL REFERENCES USUARIO(ID_USER),
    NOMBRE_DESCRIPTIVO   VARCHAR2(40)   NOT NULL,
    ANIO_INICIO          NUMBER(4)      NOT NULL,
    MES_INICIO           NUMBER(2)      NOT NULL CHECK (MES_INICIO BETWEEN 1 AND 12),
    ANIO_FIN             NUMBER(4)      NOT NULL,
    MES_FIN              NUMBER(2)      NOT NULL CHECK (MES_FIN BETWEEN 1 AND 12),
    TOTAL_INGRESOS       DECIMAL(10,2)  DEFAULT 0,
    TOTAL_GASTOS         DECIMAL(10,2)  DEFAULT 0,
    TOTAL_AHORRO         DECIMAL(10,2)  DEFAULT 0,
    FECHA_HORA_CREACION  TIMESTAMP      DEFAULT SYSTIMESTAMP,
    ESTADO_PRESUPUESTO   VARCHAR2(10)   DEFAULT 'activo'
                         CHECK (ESTADO_PRESUPUESTO IN ('activo','cerrado','borrador')),
    CONSTRAINT CHK_PERIODO CHECK (
        ANIO_FIN > ANIO_INICIO OR
        (ANIO_FIN = ANIO_INICIO AND MES_FIN >= MES_INICIO)
    )
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA    VARCHAR2(10)  PRIMARY KEY,
    NOMBRE          VARCHAR2(50)  NOT NULL,
    DESCRIPCION     VARCHAR2(100),
    TIPO            VARCHAR2(10)  NOT NULL CHECK (TIPO IN ('ingreso','gasto','ahorro')),
    NOMBRE_ICON_UI  VARCHAR2(20),
    COLOR_HEX       VARCHAR2(7),
    ORDEN           NUMBER        DEFAULT 0 CHECK (ORDEN >= 0)
);

CREATE TABLE SUBCATEGORIA (
    ID_SUBCATEGORIA  VARCHAR2(10)  PRIMARY KEY,
    ID_CATEGORIA     VARCHAR2(10)  NOT NULL REFERENCES CATEGORIA(ID_CATEGORIA),
    NOMBRE           VARCHAR2(50)  NOT NULL,
    DESCRIPCION      VARCHAR2(100),
    ACTIVA           NUMBER(1)     DEFAULT 1 CHECK (ACTIVA IN (0,1)),
    SUB_POR_DEFECTO  NUMBER(1)     DEFAULT 0 CHECK (SUB_POR_DEFECTO IN (0,1))
);

CREATE TABLE PRESUPUESTO_DETALLE (
    ID_DETALLE       VARCHAR2(10)   PRIMARY KEY,
    ID_PRESUPUESTO   VARCHAR2(10)   NOT NULL REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
    ID_SUBCATEGORIA  VARCHAR2(10)   NOT NULL REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
    MONTO            DECIMAL(10,2)  NOT NULL,
    JUSTIFICACION    VARCHAR2(100),
    CONSTRAINT UQ_DETALLE    UNIQUE (ID_PRESUPUESTO, ID_SUBCATEGORIA),
    CONSTRAINT CHK_MONTO_DET CHECK (MONTO > 0)
);

CREATE TABLE OBLIGACION_FIJA (
    ID_OBLIGACION    VARCHAR2(10)   PRIMARY KEY,
    ID_USER          VARCHAR2(10)   NOT NULL REFERENCES USUARIO(ID_USER),
    ID_SUBCATEGORIA  VARCHAR2(10)   NOT NULL REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
    NOMBRE           VARCHAR2(50)   NOT NULL,
    DESCRIPCION      VARCHAR2(100),
    MONTO            DECIMAL(10,2)  NOT NULL,
    DIA              NUMBER(2)      NOT NULL CHECK (DIA BETWEEN 1 AND 31),
    VIGENTE          NUMBER(1)      DEFAULT 1 CHECK (VIGENTE IN (0,1)),
    FECHA_INICIO     DATE           NOT NULL,
    FECHA_FIN        DATE,
    CONSTRAINT CHK_MONTO_OBL  CHECK (MONTO > 0),
    CONSTRAINT CHK_FECHAS_OBL CHECK (FECHA_FIN IS NULL OR FECHA_FIN > FECHA_INICIO)
);

CREATE TABLE TRANSACCION (
    ID_TRANSACCION       VARCHAR2(10)   PRIMARY KEY,
    ID_USER              VARCHAR2(10)   NOT NULL REFERENCES USUARIO(ID_USER),
    ID_PRESUPUESTO       VARCHAR2(10)   NOT NULL REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
    ID_SUBCATEGORIA      VARCHAR2(10)   NOT NULL REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
    ANIO                 NUMBER(4)      NOT NULL,
    MES                  NUMBER(2)      NOT NULL CHECK (MES BETWEEN 1 AND 12),
    TIPO                 VARCHAR2(15)   NOT NULL CHECK (TIPO IN ('ingreso','gasto','ahorro')),
    DESCRIPCION          VARCHAR2(100)  NOT NULL,
    MONTO                DECIMAL(10,2)  NOT NULL,
    FECHA_TRANSACCION    DATE           NOT NULL,
    METODO_PAGO          VARCHAR2(20)   DEFAULT 'efectivo'
                         CHECK (METODO_PAGO IN ('efectivo','tarjeta_debito','tarjeta_credito','transferencia')),
    NUM_FACTURA          VARCHAR2(20),
    OBSERVACIONES        VARCHAR2(100),
    FECHA_HORA_REGISTRO  TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_MONTO_TRX CHECK (MONTO > 0)
);

CREATE TABLE OBLIGACION_TRANSACCION (
    ID_TRANSACCION  VARCHAR2(10)  PRIMARY KEY REFERENCES TRANSACCION(ID_TRANSACCION),
    ID_OBLIGACION   VARCHAR2(10)  NOT NULL    REFERENCES OBLIGACION_FIJA(ID_OBLIGACION)
);

-- ============================================================
-- ÍNDICES
-- ============================================================
CREATE INDEX IDX_TRANSACCION_PERIODO  ON TRANSACCION(ANIO, MES);
CREATE INDEX IDX_TRANSACCION_SUBCAT   ON TRANSACCION(ID_SUBCATEGORIA);
CREATE INDEX IDX_TRANSACCION_PRESUP   ON TRANSACCION(ID_PRESUPUESTO);
CREATE INDEX IDX_SUBCATEGORIA_CAT     ON SUBCATEGORIA(ID_CATEGORIA);
CREATE INDEX IDX_PRESUPUESTO_USER     ON PRESUPUESTO(ID_USER);

-- ============================================================
-- TRIGGERS DE ID AUTOMÁTICO 
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_ID_USUARIO
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    :NEW.ID_USER := 'USR' || LPAD(SEQ_USUARIO.NEXTVAL, 3, '0');
END TRG_ID_USUARIO;
/

CREATE OR REPLACE TRIGGER TRG_ID_PRESUPUESTO
BEFORE INSERT ON PRESUPUESTO
FOR EACH ROW
BEGIN
    :NEW.ID_PRESUPUESTO := 'PRE' || LPAD(SEQ_PRESUPUESTO.NEXTVAL, 3, '0');
END TRG_ID_PRESUPUESTO;
/



CREATE OR REPLACE TRIGGER TRG_ID_CATEGORIA
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    :NEW.ID_CATEGORIA := 'CAT' || LPAD(SEQ_CATEGORIA.NEXTVAL, 3, '0');
END TRG_ID_CATEGORIA;
/



CREATE OR REPLACE TRIGGER TRG_ID_SUBCATEGORIA
BEFORE INSERT ON SUBCATEGORIA
FOR EACH ROW
BEGIN
    -- Aplica tanto para subcategorías manuales como
    -- para las creadas automáticamente por TRG_SUBCAT_DEFECTO
    IF :NEW.ID_SUBCATEGORIA IS NULL THEN
        :NEW.ID_SUBCATEGORIA := 'SUB' || LPAD(SEQ_SUBCATEGORIA.NEXTVAL, 3, '0');
    END IF;
END TRG_ID_SUBCATEGORIA;
/



CREATE OR REPLACE TRIGGER TRG_ID_DETALLE
BEFORE INSERT ON PRESUPUESTO_DETALLE
FOR EACH ROW
BEGIN
    :NEW.ID_DETALLE := 'DET' || LPAD(SEQ_DETALLE.NEXTVAL, 3, '0');
END TRG_ID_DETALLE;
/



CREATE OR REPLACE TRIGGER TRG_ID_OBLIGACION
BEFORE INSERT ON OBLIGACION_FIJA
FOR EACH ROW
BEGIN
    :NEW.ID_OBLIGACION := 'OBL' || LPAD(SEQ_OBLIGACION.NEXTVAL, 3, '0');
END TRG_ID_OBLIGACION;
/



CREATE OR REPLACE TRIGGER TRG_ID_TRANSACCION
BEFORE INSERT ON TRANSACCION
FOR EACH ROW
BEGIN
    :NEW.ID_TRANSACCION := 'TRX' || LPAD(SEQ_TRANSACCION.NEXTVAL, 3, '0');
END TRG_ID_TRANSACCION;
/
